Repository Track-1/client, pull requests merged in 2023-07, with the labels that each got.

#603 Fix#602 common/fix
  public/_redirects
  src/@components/@common/categoryList.tsx
  src/@components/@common/profileEditInfo.tsx
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/upload/uploadInfo.tsx
  src/assets/icon/eventPinkTextIc.svg
  src/assets/icon/eventSelectTextIc.svg
  src/assets/icon/eventTextIc.svg
  src/assets/index.ts
  src/core/constants/categories.ts
  src/core/tracks/categorySelectedCheck.ts
  src/mocks/categoryDummy.json
  src/recoil/categorySelect.ts
  src/type/CategoryChecksType.ts
Labels: feat-function, 지수

#605 [ fix ] recoil-persist 캐시 저장되는 문제 해결
  src/@pages/mainPage.tsx
Labels: fix, 지수

#607 [ fix ] 모든 리코일 삭제되는 문제 해결
  src/@components/@common/categoryList.tsx
  src/@components/login/loginInput.tsx
  src/@pages/mainPage.tsx
Labels: feat-function, 지수

#595 Feat#589 upload/UI
  package.json
  src/@components/@common/upload/common/CategotyInfo.tsx
  src/@components/@common/upload/common/DescriptionInfo.tsx
  src/@components/@common/upload/common/FileUploadInfo.tsx
  src/@components/@common/upload/common/HashtagInfo.tsx
  src/@components/@common/upload/common/TextLength.tsx
  src/@components/@common/upload/common/UploadBody.tsx
  src/@components/@common/upload/common/UploadHeader.tsx
  src/@components/@common/upload/common/UploadInfo.tsx
  src/@components/@common/upload/common/UploadInfoBox.tsx
  src/@components/@common/upload/common/UploadTitle.tsx
  src/@components/@common/upload/index.tsx
  src/@components/@common/upload/producer/ProducerLayout.tsx
  src/@components/@common/upload/producer/ProducerUploadImage.tsx
  src/@components/@common/upload/vocal/VocalLayout.tsx
  src/@components/@common/upload/vocal/VocalUploadImage.tsx
  src/@components/upload/test
  src/@pages/uploadPage.tsx
  src/Router.tsx
  src/assets/icon/categoryDropDownIc.svg
  src/assets/icon/folderUploadIc.svg
  src/assets/icon/uploadCategoryIc.svg
  src/assets/icon/uploadDescriptionIc.svg
  src/assets/icon/uploadFileChangeIc.svg
  src/assets/icon/uploadFileIc.svg
  src/assets/image/uploadAbleBtnImg.png
  src/assets/image/uploadProducerDefaultImg .png
  src/assets/image/uploadUnableBtnImg.png
  src/assets/image/uploadVocalDefaultImg.png
  src/assets/image/uploadVocalLayoutImg.png
  src/assets/index.ts
  src/core/common/fileSize.ts
  src/core/common/test
  src/core/common/textLimit.ts
  src/hooks/common/test
  src/hooks/common/useInputText.tsx
  src/hooks/common/useUploadAudioFile.tsx
  src/hooks/common/useUploadImageFile.tsx
  src/hooks/queries/upload/upload.ts
  src/hooks/upload/test
  src/hooks/upload/useUploadInitValue.tsx
  src/recoil/upload/test
  src/recoil/upload/uploadData.ts
  src/style/globalStyle.ts
  src/type/common/audioFileType.ts
  src/type/common/imageFileType.ts
  src/type/common/test
  src/type/common/textLimitType.ts
  src/type/upload/test
  src/type/upload/uploadinitType.ts
  src/type/upload/useUploadDataType.ts
  src/utils/common/checkAudioFileType.ts
  src/utils/common/checkEnterCount.ts
  src/utils/common/checkMaxInputLength.ts
  src/utils/upload/test
  yarn.lock
Labels: feat-UI, 명헌
