Repository Track-1/client, pull requests merged in 2023-02, with the labels that each got.

#168 Release1.0#165 track post/refactor
  src/@components/@common/player.tsx
  src/@components/trackPost/commentHeader.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/trackPostPage.tsx
  src/type/audioTypes.ts
  src/utils/hooks/usePlayerInfos.ts
Labels: feat-function, refactor, 지영

#166 Release1.0#157 qa/upload page
  src/@components/@common/uploadHeader.tsx
  src/@components/@common/uploadInfo.tsx
  src/@components/upload/trackUpload.tsx
  src/@components/upload/vocalUpload.tsx
  src/@pages/uploadPage.tsx
  src/core/api/upload.ts
  src/core/constants/fileSize.ts
  src/type/uploadInfoDataType.ts
  src/utils/common/eventType.ts
  src/utils/common/userType.ts
  src/utils/uploadPage/maxLength.ts
  src/utils/uploadPage/uploadImage.ts
Labels: fix, refactor, 명헌

#170 Release1.0#167 producer profile page/refactor
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@pages/producerProfilePage.tsx
  src/core/constants/categories.ts
  src/utils/common/compareIndex.ts
Labels: refactor, 명헌

#171 Release1.0#169 track search/refactor
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
  src/utils/hooks/usePlay.ts
  src/utils/hooks/usePlayer.ts
  src/utils/hooks/usePlayerInfos.ts
Labels: feat-function, refactor, 지영

#175 Release1.0#173 upload page/refactor
  src/@components/@common/uploadHeader.tsx
  src/@components/@common/uploadInfo.tsx
  src/@components/upload/trackUpload.tsx
  src/@components/upload/vocalUpload.tsx
  src/@pages/uploadPage.tsx
  src/type/uploadInfoDataType.ts
  src/utils/common/userType.ts
  src/utils/hooks/useHover.ts
  src/utils/uploadPage/uploadImage.ts
Labels: feat-function, refactor, 명헌
