Repository Track-1/client, pull requests merged in 2023-11, with the labels that each got.

#827 [ fix ] - 근원이가 몰랐으면하는 타이틀 입력창 스타일 변경
  src/@components/upload/uploadTitle.tsx
Labels: fix, 명헌

#835 Fix#834 track post/animation
  src/@components/@common/player.tsx
  src/@components/trackPost/audioJacketImage.tsx
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/index.tsx
Labels: fix, 지수

#833 Hotfix#832 common/qa
  src/@components/@common/player.tsx
  src/@components/main/renewal/recentTrackItem.tsx
  src/@components/trackPost/index.tsx
  src/@components/upload/descriptionInput.tsx
  src/@components/upload/uploadTitle.tsx
  src/core/common/textLimit.ts
Labels: fix, 명헌, code-review

#828 ✅refactor✅ Feat#819 forgotPassword/refactor
  src/@components/@common/styledComponents.ts
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/type/user.ts
Labels: refactor, 지영
