Repository Track-1/client, pull requests merged in 2023-12, with the labels that each got.

#843 Feat#842 common/layout
  .prettierrc.js
  apps/mobile/src/App.tsx
  apps/mobile/src/components/footer.tsx
  apps/mobile/src/components/header.tsx
  apps/mobile/src/components/layout.tsx
  apps/mobile/src/components/layout/emptyLayout.tsx
  apps/mobile/src/components/layout/headerFooterLayout.tsx
  apps/mobile/src/components/layout/headerLayout.tsx
  apps/mobile/src/components/layout/index.tsx
  apps/mobile/src/components/main/index.tsx
  apps/mobile/src/index.tsx
  apps/mobile/src/pages/mainPage.tsx
  packages/eslint-config-custom/index.js
  packages/eslint-config-custom/package.json
  packages/eslint-config-custom/prettier-preset.js
  packages/eslint-config-custom/react.js
  packages/tsconfig/base.json
  packages/tsconfig/package.json
Labels: 명헌, code-review

#879 Feat#877 track search/page
  apps/mobile/src/assets/icon/filterIc.svg
  apps/mobile/src/assets/icon/moreDotIc.svg
  apps/mobile/src/assets/icon/playingIc.svg
  apps/mobile/src/assets/index.ts
  apps/mobile/src/components/common/Form/playTrackForm.tsx
  apps/mobile/src/components/common/Player/player.tsx
  apps/mobile/src/components/common/Text/index.tsx
  apps/mobile/src/components/login/loginInput.tsx
  apps/mobile/src/components/main/index.tsx
  apps/mobile/src/components/producerProfile/index.tsx
  apps/mobile/src/components/trackSearch/index.tsx
  apps/mobile/src/components/trackSearch/trackSearchItem.tsx
  apps/mobile/src/context/playerContext.tsx
  apps/mobile/src/core/common/zIndex.ts
  apps/mobile/src/hooks/common/usePlay.ts
  apps/mobile/src/pages/mainPage.tsx
  apps/mobile/src/pages/trackSearchPage.tsx
Labels: code-review

#874 [ feat ] 회원가입 1단계 role 구현
  apps/mobile/src/components/signUp/SignupStep/Role/Card.tsx
  apps/mobile/src/components/signUp/SignupStep/Role/index.tsx
  apps/mobile/src/recoil/common/role.ts
  apps/mobile/src/type/common/userType.ts
Labels: 지수
