Repository Track-1/client, pull requests merged in 2023-01, with the labels that each got.

#29 Feat#23 track search/fix track list & player
  src/@components/@common/player.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/trackListHeader.tsx
  src/@pages/trackSearchPage.tsx
  src/mocks/tracksListDummy.json
  src/recoil/player.ts
Labels: feat-function, fix, refactor, 지수

#27 Feat#25 track post/review
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/trackPostPage.tsx
  src/assets/icon/addCommentIc.svg
  src/assets/icon/commentBtnIC.svg
  src/assets/icon/playBtnIc.svg
  src/assets/icon/uploadIc.svg
  src/assets/image/profileDummyImg.png
  src/assets/index.ts
  src/core/trackPost/userComments.ts
  src/style/theme.ts
  src/type/uploadDataType.ts
  src/type/userCommentsType.ts
Labels: feat-UI, feat-function, 지영

#26 Feat#22 track search/fix header & category list
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/trackSearch/categoryList.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/trackListHeader.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/icon/BalladPinkTextIc.svg
  src/assets/icon/BalladSelectTextIc.svg
  src/assets/icon/EDMPinkTextIc.svg
  src/assets/icon/EDMSelectTextIc.svg
  src/assets/icon/FunkPinkTextIc.svg
  src/assets/icon/FunkSelectTextIc.svg
  src/assets/icon/HiphopPinkTextIc.svg
  src/assets/icon/HiphopSelectTextIc.svg
  src/assets/icon/HousePinkTextIc.svg
  src/assets/icon/HouseSelectTextIc.svg
  src/assets/icon/JazzPinkTextIc.svg
  src/assets/icon/JazzSelectTextIc.svg
  src/assets/icon/PinkXIc.svg
  src/assets/icon/PopPinkTextIc.svg
  src/assets/icon/PopSelectTextIc.svg
  src/assets/icon/PortfolioIc.svg
  src/assets/icon/PortfolioTextIc.svg
  src/assets/icon/R&BPinkTextIc.svg
  src/assets/icon/R&BSelectTextIc.svg
  src/assets/icon/RockPinkTextIc.svg
  src/assets/icon/RockSelectTextIc.svg
  src/assets/icon/TrackSearchingPinkIc.svg
  src/assets/icon/TrackSearchingTextIc.svg
  src/assets/icon/TracksSelectTextIc.svg
  src/assets/icon/TracksTextIc.svg
  src/assets/icon/UnionIc.svg
  src/assets/icon/VocalSearchingIc.svg
  src/assets/icon/VocalSearchingTextIc.svg
  src/assets/icon/VocalsSelectTextIc.svg
  src/assets/icon/VocalsTextIc.svg
  src/assets/index.ts
  src/mocks/categoryDummy.json
  src/mocks/tracksListDummy.json
  src/recoil/categorySelect.ts
  src/recoil/player.ts
  tsconfig.json
Labels: feat-UI, feat-function, fix, refactor, 지수

#24 Feat#10 track post/post
  src/@components/@common/backButton.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/hashTag.tsx
  src/@pages/trackPostPage.tsx
  src/assets/icon/backBtnIc.svg
  src/assets/icon/categoryIc.svg
  src/assets/icon/closedBtnIc.svg
  src/assets/icon/closedWithXIc.svg
  src/assets/icon/deleteIc.svg
  src/assets/icon/descriptionIc.svg
  src/assets/icon/downloadBtnIc.svg
  src/assets/icon/editBtnIc.svg
  src/assets/icon/editIc.svg
  src/assets/icon/hashtagIc.svg
  src/assets/icon/openedIc.svg
  src/assets/icon/pauseBtnIc.svg
  src/assets/image/playImg.png
  src/assets/index.ts
  src/style/globalStyle.ts
  src/style/theme.ts
Labels: feat-UI, 지영

#21 Feat#15 track search/player
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/trackSearch/categoryList.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/trackListHeader.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/icon/BalladPinkTextIc.svg
  src/assets/icon/BalladSelectTextIc.svg
  src/assets/icon/EDMPinkTextIc.svg
  src/assets/icon/EDMSelectTextIc.svg
  src/assets/icon/FunkPinkTextIc.svg
  src/assets/icon/FunkSelectTextIc.svg
  src/assets/icon/HiphopPinkTextIc.svg
  src/assets/icon/HiphopSelectTextIc.svg
  src/assets/icon/HousePinkTextIc.svg
  src/assets/icon/HouseSelectTextIc.svg
  src/assets/icon/HoverPlayIc.svg
  src/assets/icon/JazzPinkTextIc.svg
  src/assets/icon/JazzSelectTextIc.svg
  src/assets/icon/PinkXIc.svg
  src/assets/icon/PlayIc.svg
  src/assets/icon/PopPinkTextIc.svg
  src/assets/icon/PopSelectTextIc.svg
  src/assets/icon/PortfolioIc.svg
  src/assets/icon/PortfolioTextIc.svg
  src/assets/icon/QuitIc.svg
  src/assets/icon/R&BPinkTextIc.svg
  src/assets/icon/R&BSelectTextIc.svg
  src/assets/icon/RockPinkTextIc.svg
  src/assets/icon/RockSelectTextIc.svg
  src/assets/icon/TrackSearchingPinkIc.svg
  src/assets/icon/TrackSearchingTextIc.svg
  src/assets/icon/TracksSelectTextIc.svg
  src/assets/icon/TracksTextIc.svg
  src/assets/icon/UnionIc.svg
  src/assets/icon/VocalSearchingIc.svg
  src/assets/icon/VocalSearchingTextIc.svg
  src/assets/icon/VocalsSelectTextIc.svg
  src/assets/icon/VocalsTextIc.svg
  src/assets/index.ts
  src/mocks/categoryDummy.json
  src/mocks/tracksListDummy.json
  src/recoil/categorySelect.ts
  src/recoil/player.ts
  src/recoil/tracksOrVocalsCheck.ts
  src/style/theme.ts
  tsconfig.json
Labels: feat-UI, feat-function, 지수

#20 Feat#14 track search/track list
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/trackSearch/categoryList.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/trackListHeader.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/icon/BalladPinkTextIc.svg
  src/assets/icon/BalladSelectTextIc.svg
  src/assets/icon/CategoryTextIc.svg
  src/assets/icon/EDMPinkTextIc.svg
  src/assets/icon/EDMSelectTextIc.svg
  src/assets/icon/FunkPinkTextIc.svg
  src/assets/icon/FunkSelectTextIc.svg
  src/assets/icon/HashtagTextIc.svg
  src/assets/icon/HiphopPinkTextIc.svg
  src/assets/icon/HiphopSelectTextIc.svg
  src/assets/icon/HousePinkTextIc.svg
  src/assets/icon/HouseSelectTextIc.svg
  src/assets/icon/HoverPauseIc.svg
  src/assets/icon/HoverPlayIc.svg
  src/assets/icon/JazzPinkTextIc.svg
  src/assets/icon/JazzSelectTextIc.svg
  src/assets/icon/PauseIc.svg
  src/assets/icon/PinkXIc.svg
  src/assets/icon/PlayIc.svg
  src/assets/icon/PopPinkTextIc.svg
  src/assets/icon/PopSelectTextIc.svg
  src/assets/icon/PortfolioIc.svg
  src/assets/icon/PortfolioTextIc.svg
  src/assets/icon/ProducerCategoryTextIc.svg
  src/assets/icon/QuitIc.svg
  src/assets/icon/R&BPinkTextIc.svg
  src/assets/icon/R&BSelectTextIc.svg
  src/assets/icon/RockPinkTextIc.svg
  src/assets/icon/RockSelectTextIc.svg
  src/assets/icon/TitleTextIc.svg
  src/assets/icon/TrackSearchingPinkIc.svg
  src/assets/icon/TrackSearchingTextIc.svg
  src/assets/icon/TracksSelectTextIc.svg
  src/assets/icon/TracksTextIc.svg
  src/assets/icon/UnionIc.svg
  src/assets/icon/VocalSearchingIc.svg
  src/assets/icon/VocalSearchingTextIc.svg
  src/assets/icon/VocalsSelectTextIc.svg
  src/assets/icon/VocalsTextIc.svg
  src/assets/image/thumbnailImg.png
  src/assets/index.ts
  src/mocks/categoryDummy.json
  src/mocks/tracksListDummy.json
  src/recoil/categorySelect.ts
  src/recoil/player.ts
  src/recoil/tracksOrVocalsCheck.ts
  src/style/theme.ts
  tsconfig.json
Labels: feat-UI, feat-function, 지수

#18 Feat#4 main page/footer
  src/@components/@common/footer.tsx
  src/assets/image/bannerImg.png
  src/assets/image/𝐅𝐚𝐭𝐞 __ Genshin Impact x (Fem!reader)  - Character info.jpeg
Labels: feat-UI, feat-function, 명헌

#17 Feat#5 mainPage/main
  src/@components/@common/footer.tsx
  src/@pages/mainPage.tsx
  src/assets/icon/tracksTextIc.svg
  src/assets/icon/vocalsTextIc.svg
  src/assets/image/hoverTracksImg.png
  src/assets/image/hoverVocalsImg.png
  src/assets/image/mainBackgroundImg.png
  src/assets/image/mainSloganImg.png
  src/assets/index.ts
Labels: feat-UI, feat-function, fix, refactor, 명헌

#16 Feat#13 track search/track list header
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/trackSearch/categoryList.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/trackListHeader.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/icon/BalladPinkTextIc.svg
  src/assets/icon/BalladSelectTextIc.svg
  src/assets/icon/CategoryTextIc.svg
  src/assets/icon/EDMPinkTextIc.svg
  src/assets/icon/EDMSelectTextIc.svg
  src/assets/icon/FunkPinkTextIc.svg
  src/assets/icon/FunkSelectTextIc.svg
  src/assets/icon/HashtagTextIc.svg
  src/assets/icon/HiphopPinkTextIc.svg
  src/assets/icon/HiphopSelectTextIc.svg
  src/assets/icon/HousePinkTextIc.svg
  src/assets/icon/HouseSelectTextIc.svg
  src/assets/icon/HoverPauseIc.svg
  src/assets/icon/HoverPlayIc.svg
  src/assets/icon/JazzPinkTextIc.svg
  src/assets/icon/JazzSelectTextIc.svg
  src/assets/icon/PauseIc.svg
  src/assets/icon/PinkXIc.svg
  src/assets/icon/PlayIc.svg
  src/assets/icon/PopPinkTextIc.svg
  src/assets/icon/PopSelectTextIc.svg
  src/assets/icon/PortfolioIc.svg
  src/assets/icon/PortfolioTextIc.svg
  src/assets/icon/ProducerCategoryTextIc.svg
  src/assets/icon/ProducerTextIc.svg
  src/assets/icon/QuitIc.svg
  src/assets/icon/R&BPinkTextIc.svg
  src/assets/icon/R&BSelectTextIc.svg
  src/assets/icon/RockPinkTextIc.svg
  src/assets/icon/RockSelectTextIc.svg
  src/assets/icon/TitleTextIc.svg
  src/assets/icon/TrackSearchingPinkIc.svg
  src/assets/icon/TrackSearchingTextIc.svg
  src/assets/icon/TracksSelectTextIc.svg
  src/assets/icon/TracksTextIc.svg
  src/assets/icon/UnionIc.svg
  src/assets/icon/VocalSearchingIc.svg
  src/assets/icon/VocalSearchingTextIc.svg
  src/assets/icon/VocalTextIc.svg
  src/assets/icon/VocalsSelectTextIc.svg
  src/assets/icon/VocalsTextIc.svg
  src/assets/icon/trackListHeaderSloganIc.svg
  src/assets/image/thumbnailImg.png
  src/assets/index.ts
  src/mocks/categoryDummy.json
  src/mocks/tracksListDummy.json
  src/recoil/categorySelect.ts
  src/recoil/player.ts
  src/recoil/tracksOrVocalsCheck.ts
  src/style/theme.ts
  tsconfig.json
Labels: feat-UI, 지수

#11 Feat#3 main page/header
  src/@components/@common/footer.tsx
  src/@components/@common/header.tsx
  src/@components/@common/mainHeader.tsx
  src/@pages/mainPage.tsx
  src/assets/icon/logoIC.svg
  src/assets/icon/mypageTextIC.svg
  src/assets/icon/userIC.svg
  src/assets/image/sloganImg.svg
  src/assets/index.ts
Labels: feat-UI, fix, refactor, 명헌

#33 Feat#30 common/msw
  package.json
  public/mockServiceWorker.js
  src/core/api/axios.ts
  src/core/api/common/axios.ts
  src/core/api/common/path.ts
  src/core/api/myPage.ts
  src/core/api/producerProfile.ts
  src/core/api/trackPost.ts
  src/core/api/trackSearch.ts
  src/core/api/trackUpload.ts
  src/core/api/vocalProfile.ts
  src/core/api/vocalSearch.ts
  src/index.tsx
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/myPage.ts
  src/mocks/handlers/producerProfile.ts
  src/mocks/handlers/trackPost.ts
  src/mocks/handlers/trackSearch.ts
  src/mocks/handlers/trackUpload.ts
  src/mocks/handlers/vocalProfile.ts
  src/mocks/handlers/vocalSearch.ts
  yarn.lock
Labels: feat-function, 지영

#45 Feat#42 producer profile/slide
  src/@components/@common/player.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/trackPost/hashTag.tsx
  src/@pages/producerProfilePage.tsx
  src/assets/icon/portfolioPlayBtnIc.svg
  src/assets/icon/rightArrorIc.svg
  src/assets/image/portFolioImg.png
  src/assets/image/producerGradientImg.png
  src/assets/index.ts
  src/mocks/handlers/producerProfile.ts
  src/type/producerProfile.ts
Labels: feat-UI, feat-function, 지영

#41 Feat#37 common/portfolios inform
  src/@components/@common/portfoiloViewMoreButton.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@components/vocalProfile/vocalProfileShadow.tsx
  src/@pages/vocalProfilePage.tsx
  src/assets/icon/blankIc.svg
  src/assets/icon/ellipsisIc.svg
  src/assets/icon/pencilUpdateIc.svg
  src/assets/icon/producerPortfolioTitleTextIc.svg
  src/assets/icon/producerProfileTitleTextIc.svg
  src/assets/icon/producerProfileUploadeModalIc.svg
  src/assets/icon/producerVocalSearchingArrowIc.svg
  src/assets/icon/producerVocalSearchingViewMoreTextIc.svg
  src/assets/icon/setIsTitleIc.svg
  src/assets/icon/trashDeleteIc.svg
  src/assets/icon/uploadButtonBlankIc.svg
  src/assets/icon/uploadButtonIc.svg
  src/assets/icon/vocalPortfolioTitleTextIc.svg
  src/assets/index.ts
  src/mocks/handlers/producerProfile.ts
  src/mocks/handlers/vocalProfile.ts
  src/recoil/uploadButtonClicked.tsx
  src/type/profilePropsType.ts
Labels: feat-UI, feat-function, 지수

#40 Feat#28 common/refactor
  __test__/sample.test.ts
  __tests__/sample.test.ts
  package.json
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/trackPost/commentHeader.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/trackListHeader.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@pages/mainPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/tracksPage.tsx
  src/@pages/vocalsPage.tsx
  src/Router.tsx
  src/assets/icon/closeBtnIc.svg
  src/assets/icon/commentBtnIC.svg
  src/assets/icon/smallPlayBtnIc.svg
  src/assets/index.ts
  src/core/common/categoryHeader.ts
  src/core/main.ts/testPage.ts
  src/core/producerProfile/testPage.ts
  src/core/trackPost/testPage.ts
  src/core/tracks/categorySelectedCheck.ts
  src/core/vocalProfile/testPage.ts
  src/core/vocals/test.ts
  src/core/vocals/testPage.ts
  src/recoil/playDatas.ts
  src/recoil/player.ts
  src/recoil/test.ts
  src/recoil/tracksOrVocalsCheck.ts
  src/style/theme.ts
  src/type/CategoryChecksType.ts
  src/utils/hooks/test.ts
  src/utils/hooks/testPage.ts
  src/utils/testPage.ts
Labels: feat-function, fix, refactor, 지영

#34 Feat#31 vocal profile/vocal profile list
  .eslintrc.ts
  jest.config.js
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/@common/portfoiloViewMoreButton.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@components/vocalProfile/vocalProfileShadow.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/assets.d.ts
  src/assets/icon/blankIc.svg
  src/assets/icon/ellipsisIc.svg
  src/assets/icon/pencilUpdateIc.svg
  src/assets/icon/producerPortfolioTitleTextIc.svg
  src/assets/icon/producerProfileTitleTextIc.svg
  src/assets/icon/producerProfileUploadeModalIc.svg
  src/assets/icon/producerVocalSearchingArrowIc.svg
  src/assets/icon/producerVocalSearchingViewMoreTextIc.svg
  src/assets/icon/setIsTitleIc.svg
  src/assets/icon/trashDeleteIc.svg
  src/assets/icon/uploadButtonBlankIc.svg
  src/assets/icon/uploadButtonIc.svg
  src/assets/icon/vocalPortfolioTitleTextIc.svg
  src/assets/icon/vocalProfileBlurPauseIc.svg
  src/assets/icon/vocalProfileBlurPlayIc.svg
  src/assets/icon/vocalProfileListContainerIc.svg
  src/assets/icon/vocalProfileShadowIc.svg
  src/assets/icon/vocalsFontIc.svg
  src/assets/image/vocalPortfolioList1.png
  src/assets/image/vocalPortfolioList2.png
  src/assets/image/vocalPortfolioList3.png
  src/assets/image/vocalPortfolioList4.png
  src/assets/image/vocalPortfolioList5.png
  src/assets/index.ts
  src/core/api/vocalProfile.ts
  src/mocks/categoryDummy.json
  src/mocks/handlers/vocalProfile.ts
  src/mocks/tracksListDummy.json
  src/mocks/vocalProfileDummy.json
  src/recoil/categorySelect.ts
  src/recoil/uploadButtonClicked.tsx
  src/type/headerProps.ts
  src/type/profilePropsType.ts
  src/type/test.ts
  tsconfig.json
Labels: feat-UI, feat-function, 지수

#46 Feat#44 main page/main
  src/@pages/mainPage.tsx
  src/assets/icon/mainTracksTextIc.svg
  src/assets/icon/mainVocalsTextIc.svg
  src/assets/image/hoverTracksImg.png
  src/assets/image/hoverVocalsImg.png
  src/assets/image/mainBackgroundImg.png
  src/mocks/handlers/vocalSearch.ts
Labels: feat-UI, 예원

#53 Feat#50 producer profile/merge page
  src/@components/@common/portfoiloViewMoreButton.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@pages/producerProfilePage.tsx
  src/assets/icon/producerPortfolioTitleTextIc.svg
  src/assets/icon/producerProfilePauseIc.svg
  src/assets/icon/producerProfilePlayIc.svg
  src/assets/icon/producerProfilePlayPlayIc.svg
  src/assets/icon/producerProfileTitleTextIc.svg
  src/assets/index.ts
  src/mocks/handlers/producerProfile.ts
  src/type/producerProfile.ts
  src/type/profilePropsType.ts
Labels: feat-function, 지수

#55 Feat#52 common/player
  src/@components/@common/player.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@components/vocalSearch/vocalListHeader.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/audio/bonfire.mp3
  src/mocks/handlers/trackPost.ts
  src/mocks/handlers/trackSearch.ts
  src/mocks/handlers/vocalSearch.ts
  src/recoil/player.ts
  src/type/audioTypes.ts
  src/type/tracksDataType.ts
Labels: feat-function, fix, refactor, 지영

#57 Feat#54 common/msw
  src/@components/vocalSearch/vocalList copy 2.tsx
  src/@components/vocalSearch/vocalList copy.tsx
  src/@components/vocalSearch/vocalListHeader.tsx
  src/@pages/vocalsPage.tsx
  src/mocks/handlers/producerProfile.ts
  src/mocks/handlers/trackPost.ts
  src/mocks/handlers/trackSearch.ts
  src/mocks/handlers/vocalSearch.ts
Labels: 예원

#59 Feat#56 common/refactor
  src/@components/@common/portfoliosInform.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@pages/producerProfilePage.tsx
  src/mocks/handlers/producerProfile.ts
Labels: fix, refactor, 지영

#74 Feat#73 common/track post
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/trackPostPage.tsx
  src/core/api/trackPost.ts
  src/recoil/postIsCompleted.ts
  src/type/uploadData.ts
  src/type/uploadDataType.ts
  src/type/userCommentsType.ts
Labels: feat-function, 지수

#78 Feat#71 common/infinite scroll
  src/@components/trackSearch/trackList.tsx
  src/@pages/trackSearchPage.tsx
  src/core/api/trackSearch.ts
  src/recoil/categorySelect.ts
  src/recoil/infiniteScroll.ts
Labels: feat-function

#92 [ trackPost ] - 무한스크롤
  src/@components/producerProfile/producerInfos.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/producerProfilePage.tsx
Labels: feat-UI, 예원

#94 Feat#86 js/qa
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/footer.tsx
  src/@components/@common/mainHeader.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@components/vocalSearch/vocalListHeader.tsx
  src/@pages/mainPage.tsx
  src/Router.tsx
  src/assets/icon/footerTextsIc.svg
  src/assets/icon/track1MainLogoIc.svg
  src/assets/icon/trackListHeaderSloganIc.svg
  src/assets/icon/trackListHeaderSloganNewIc.svg
  src/assets/icon/vocalListHeaderSloganIc.svg
  src/assets/icon/vocalListHeaderSloganNewIc.svg
  src/assets/image/mainPageBackgroundImg.png
  src/assets/index.ts
  src/recoil/uploadButtonClicked.tsx
Labels: fix, 지수

#96 Feat#93 common/refactor
  src/@components/@common/portfoliosInform.tsx
  src/@components/@common/uploadHeader.tsx
  src/core/api/vocalProfile.ts
Labels: fix, refactor, 지영

#95 Feat#83 upload page/qa
  src/@components/@common/uploadHeader.tsx
  src/@components/@common/uploadInfo.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@pages/uploadPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/Router.tsx
  src/assets/icon/checkCategoryIc.svg
  src/assets/index.ts
  src/core/api/upload.ts
  src/type/uploadData.ts
Labels: feat-UI, feat-function, fix, 명헌

#102 Feat#100-QA/trackUpload
  src/@components/@common/categoryList.tsx
  src/@components/@common/uploadHeader.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@pages/uploadPage.tsx
  src/Router.tsx
Labels: fix, 지수

#107 Feat#103 qa/vocal search
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 지수

#114 Feat#108 qa/infinite scroll & filtering
  public/favicon.ico
  public/favicon2.ico
  public/index.html
  src/@components/@common/categoryList.tsx
  src/@components/trackSearch/trackList.tsx
  src/@pages/trackSearchPage.tsx
  src/core/api/trackSearch.ts
  src/recoil/categorySelect.ts
Labels: fix, 지수

#117 Feat#104 qa/track post page
  src/@components/@common/backButton.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/trackPostPage.tsx
  src/Router.tsx
  src/type/tracksDataType.ts
Labels: fix, 예원

#120 Feat#106 qa/upload page/post
  src/@components/@common/uploadHeader.tsx
  src/@components/upload/trackUpload.tsx
  src/@components/upload/vocalUpload.tsx
  src/core/api/upload.ts
  src/recoil/upload.ts
  src/type/uploadData.ts
Labels: feat-function, 명헌

#121 Feat#113 qa/player
  src/@components/@common/categoryList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/vocalsPage.tsx
  src/core/api/vocalSearch.ts
Labels: fix, refactor, 지영

#122 Feat#110 qa/upload page/UI
  src/@components/@common/uploadInfo.tsx
  src/assets/image/trackUploadDefaultImg.png
  src/assets/image/vocalUploadDefaultImg.png
Labels: feat-UI, fix, 명헌

#123 Feat#116 qa/mh
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@pages/trackPostPage.tsx
Labels: 명헌

#129 Feat#126 qa/js
  package.json
  src/@components/@common/portfoliosInform.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/core/api/download.ts
  yarn.lock
Labels: fix, 지수

#131 Feat#118 qa/producer profile
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@pages/vocalsPage.tsx
  src/core/api/vocalSearch.ts
  src/type/vocalsDataType.ts
Labels: feat-function, fix, 예원

#133 Feat#125 qa/upload page
  src/@components/@common/uploadHeader.tsx
  src/@components/@common/uploadInfo.tsx
  src/@components/upload/trackUpload.tsx
  src/@components/upload/vocalUpload.tsx
Labels: feat-function, fix, 명헌

#134 [ fix ] VD001 - 프로듀서 이름 클릭 시 해당 [프로듀서 프로필 페이지-타인]으로 이동
  src/@components/trackSearch/trackList.tsx
  src/@pages/producerProfilePage.tsx
  src/core/api/producerProfile.ts
  src/type/tracksDataType.ts
Labels: feat-function, fix, 명헌

#135 Feat#130 qa/vocals infinite scroll
  src/@components/trackPost/commentWrite.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalsPage.tsx
  src/core/api/vocalSearch.ts
  src/type/vocalsDataType.ts
Labels: fix, 지수

#137 [ fix ] player 오류 수정
  src/@components/@common/player.tsx
  src/@components/@common/uploadHeader.tsx
  src/@components/trackSearch/trackList.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
Labels: fix, refactor, 지영

#140 Feat#138 qa/js
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/trackPost/commentHeader.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/trackPostPage.tsx
  src/core/constants/pageCategory.ts
Labels: fix, 지수

#147 [ fix ] vocal profile 모양 수정
  src/@components/producerProfile/producerInfos.tsx
  src/@pages/producerProfilePage.tsx
  src/assets/icon/sleeperAccountIc.svg
  src/assets/index.ts
  src/recoil/categorySelect.ts
Labels: feat-function

#149 Feat#148 qa/js
  src/@pages/trackPostPage.tsx
Labels: fix, 지수

#158 Feat#155 qa/common
  src/@components/@common/player.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/trackPostPage.tsx
Labels: feat-function, fix, refactor, 지영

#162 Release1.0#161 player/custom hook
  src/@components/@common/player.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
  src/utils/hooks/usePlay.ts
  src/utils/hooks/usePlayer.ts
  src/utils/hooks/useProgress.ts
Labels: fix, refactor, 지영
