Repository Track-1/client, pull requests merged in 2023-08, with the labels that each got.

#640 Feat#638 trackpost/play
  src/@components/@common/backButton.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/playButton.tsx
  src/@pages/trackPostPage.tsx
  src/api/trackPost/closeTrack.ts
  src/api/trackPost/getTrackInfo.ts
  src/assets/icon/backButtonIc.svg
  src/assets/icon/trackPostPauseBtnIc.svg
  src/assets/icon/trackPostPlayBtnIc.svg
  src/assets/index.ts
Labels: refactor, 지수

#637 Feat#635 track post/edit
  src/@components/@common/backButton.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/playButton.tsx
  src/@components/trackPost/showMore.tsx
  src/@pages/trackPostPage.tsx
  src/api/trackPost/closeTrack.ts
  src/api/trackPost/deleteTrack.ts
  src/api/trackPost/deleteTrackComment.ts
  src/api/trackPost/getTrackInfo.ts
  src/assets/icon/backButtonIc.svg
  src/assets/icon/deleteIc.svg
  src/assets/icon/editBtnIc.svg
  src/assets/icon/editIc.svg
  src/assets/icon/trackPostPauseBtnIc.svg
  src/assets/icon/trackPostPlayBtnIc.svg
  src/assets/index.ts
  src/hooks/trackPost/useGetTrackInfo.ts
Labels: refactor, 지수

#636 Feat#634 track post/download
  src/@components/@common/backButton.tsx
  src/@components/trackPost/download.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/playButton.tsx
  src/@components/trackPost/showMore.tsx
  src/@pages/trackPostPage.tsx
  src/api/trackPost/closeTrack.ts
  src/api/trackPost/deleteTrack.ts
  src/api/trackPost/deleteTrackComment.ts
  src/api/trackPost/getFileLink.ts
  src/api/trackPost/getTrackInfo.ts
  src/assets/icon/backButtonIc.svg
  src/assets/icon/closedBtnIc.svg
  src/assets/icon/closedWithXIc.svg
  src/assets/icon/deleteIc.svg
  src/assets/icon/downloadBtnIc.svg
  src/assets/icon/editBtnIc.svg
  src/assets/icon/editIc.svg
  src/assets/icon/openedIc.svg
  src/assets/icon/trackPostPauseBtnIc.svg
  src/assets/icon/trackPostPlayBtnIc.svg
  src/assets/index.ts
  src/core/common/queriesKey.ts
  src/hooks/trackPost/useGetTrackInfo.ts
Labels: refactor, 지수

#631 Feat#630 trackpost/producer profile
  src/@components/@common/backButton.tsx
  src/@components/@common/hashTag.tsx
  src/@components/trackPost/audioCategory.tsx
  src/@components/trackPost/audioDescription.tsx
  src/@components/trackPost/audioHashtags.tsx
  src/@components/trackPost/audioInfo.tsx
  src/@components/trackPost/audioJacketImage.tsx
  src/@components/trackPost/download.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/playButton.tsx
  src/@components/trackPost/producerProfile.tsx
  src/@components/trackPost/showMore.tsx
  src/@pages/trackPostPage.tsx
  src/api/trackPost/closeTrack.ts
  src/api/trackPost/deleteTrack.ts
  src/api/trackPost/deleteTrackComment.ts
  src/api/trackPost/getFileLink.ts
  src/api/trackPost/getTrackInfo.ts
  src/assets/icon/backButtonIc.svg
  src/assets/icon/categoryIc.svg
  src/assets/icon/closedBtnIc.svg
  src/assets/icon/closedWithXIc.svg
  src/assets/icon/deleteIc.svg
  src/assets/icon/descriptionIc.svg
  src/assets/icon/downloadBtnIc.svg
  src/assets/icon/editBtnIc.svg
  src/assets/icon/editIc.svg
  src/assets/icon/hashtagIc.svg
  src/assets/icon/openedIc.svg
  src/assets/icon/trackPostPauseBtnIc.svg
  src/assets/icon/trackPostPlayBtnIc.svg
  src/assets/index.ts
  src/core/common/queriesKey.ts
  src/hooks/trackPost/useGetTrackInfo.ts
Labels: refactor, 지수

#626 Feat#625 signup/success
  src/@components/signUp/producerSuccess.tsx
  src/@components/signUp/producerUploadModal.tsx
  src/@components/signUp/stepFooter.tsx
  src/@components/signUp/vocalSuccess.tsx
  src/@pages/signupStepPage.tsx
  src/@pages/signupSuccessPage.tsx
  src/App.tsx
  src/assets/icon/moveTouploadPortfolioButtonIc.svg
  src/assets/icon/moveTouploadVocalSearchingButtonIc.svg
  src/assets/icon/signUpGetStartedButtonIc.svg
  src/assets/icon/signUpProducerButtonIc.svg
  src/assets/icon/signUpProducerQIc.svg
  src/assets/icon/signUpSuccessBackgroundIc.svg
  src/assets/icon/signUpVocalButtonIc.svg
  src/assets/icon/signUpVocalQIc.svg
  src/assets/index.ts
  src/hooks/common/useConventionModal.ts
  src/hooks/common/useInputText.ts
  src/hooks/common/useModal.ts
  src/hooks/common/useUploadAudioFile.ts
  src/hooks/common/useUploadImageFile.ts
  src/recoil/common/isModalOpen.ts
  src/recoil/common/role.ts
  src/utils/common/modal.ts
  yarn.lock
Labels: refactor, 지수

#628 Feat#627 trackpost/audio title
  src/@components/@common/backButton.tsx
  src/@components/@common/hashTag.tsx
  src/@components/trackPost/audioCategory.tsx
  src/@components/trackPost/audioDescription.tsx
  src/@components/trackPost/audioHashtags.tsx
  src/@components/trackPost/audioInfo.tsx
  src/@components/trackPost/audioJacketImage.tsx
  src/@components/trackPost/audioTitle.tsx
  src/@components/trackPost/download.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/playButton.tsx
  src/@components/trackPost/producerProfile.tsx
  src/@components/trackPost/showMore.tsx
  src/@components/trackPost/test
  src/@pages/trackPostPage
  src/@pages/trackPostPage.tsx
  src/Router.tsx
  src/api/common/client.ts
  src/api/trackPost/closeTrack.ts
  src/api/trackPost/deleteComment.ts
  src/api/trackPost/deleteTrack.ts
  src/api/trackPost/deleteTrackComment.ts
  src/api/trackPost/getComment.ts
  src/api/trackPost/getFileLink.ts
  src/api/trackPost/getTrackInfo.ts
  src/api/trackPost/pathTrackPost.ts
  src/api/trackPost/postComment.ts
  src/api/trackPost/updateComment.ts
  src/assets/icon/backButtonIc.svg
  src/assets/icon/categoryIc.svg
  src/assets/icon/closedBtnIc.svg
  src/assets/icon/closedWithXIc.svg
  src/assets/icon/deleteIc.svg
  src/assets/icon/descriptionIc.svg
  src/assets/icon/downloadBtnIc.svg
  src/assets/icon/editBtnIc.svg
  src/assets/icon/editIc.svg
  src/assets/icon/hashtagIc.svg
  src/assets/icon/openedIc.svg
  src/assets/icon/trackPostPauseBtnIc.svg
  src/assets/icon/trackPostPlayBtnIc.svg
  src/assets/index.ts
  src/core/common/queriesKey.ts
  src/hooks/trackPost/test
  src/hooks/trackPost/useGetTrackInfo.ts
Labels: refactor, 지수, code-review

#615 Feat#594 profile edit/image
  package.json
  src/@components/@common/backButton.tsx
  src/@components/@common/hashtag/hashtagInput.tsx
  src/@components/@common/hashtag/hashtagWarning.tsx
  src/@components/@common/hashtag/hashtagsEdit.tsx
  src/@components/@common/hashtagsEdit.tsx
  src/@components/@common/profileTitleInput.tsx
  src/@components/@common/selectCategories.tsx
  src/@components/@common/upload/common/DescriptionInfo.tsx
  src/@components/@common/upload/common/DescriptionInput.tsx
  src/@components/@common/upload/common/HashtagInfo.tsx
  src/@components/@common/upload/common/UploadHeader.tsx
  src/@components/producerProfileEdit/DescriptionInfo.tsx
  src/@components/producerProfileEdit/index.tsx
  src/@components/producerProfileEdit/producerImageEdit.tsx
  src/@components/producerProfileEdit/producerProfileBody.tsx
  src/@components/producerProfileEdit/producerProfileEditHeader.tsx
  src/@components/vocalPortfolioEdit/test
  src/@components/vocalProfileEdit/index.tsx
  src/@components/vocalProfileEdit/vocalImageEdit.tsx
  src/@components/vocalProfileEdit/vocalProfileBody.tsx
  src/@components/vocalProfileEdit/vocalSleeper.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/assets/icon/changePhotoProducerIc.svg
  src/assets/icon/changePhotoVocalIc.svg
  src/assets/icon/hashtagTitleIc.svg
  src/assets/icon/profileEditActiveButtonIc.svg
  src/assets/icon/profileEditSleepAcountTextIc.svg
  src/assets/icon/profileEditSleepAcountTitleIc.svg
  src/assets/icon/profileEditSleeperButtonIc.svg
  src/assets/index.ts
  src/core/common/hashtagInfo.ts
  src/hooks/common/useShowImage.ts
  src/style/theme.ts
  src/utils/common/checkKorean.ts
  yarn.lock
Labels: refactor

#643 Fix#642 hotfix/git error
  package.json
  src/api/trackPost/getTrackInfo.ts
  src/assets/index.ts
  yarn.lock
Labels: fix, 지수

#648 Feat#647 common/fix
  src/@components/trackPost/eachUserComment.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/upload/uploadInfo.tsx
  src/@pages/uploadPage.tsx
  src/style/globalStyle.ts
Labels: refactor, 지수

#658 Feat#657-Index/addTag
  public/index.html
Labels: feat-function, 명헌

#659 Feat#608 upload/custom hook
  README.md
  src/@components/@common/upload/common/DescriptionInfo.tsx
  src/@components/@common/upload/common/UploadBody.tsx
  src/@components/@common/upload/common/UploadHeader.tsx
  src/@components/@common/upload/common/UploadInfo.tsx
  src/@components/@common/upload/index.tsx
  src/@components/@common/upload/producer/ProducerLayout.tsx
  src/@components/@common/upload/producer/ProducerUploadImage.tsx
  src/@components/@common/upload/vocal/VocalLayout.tsx
  src/@components/@common/upload/vocal/VocalUploadImage.tsx
  src/@components/producerPortfolioEdit/index.tsx
  src/@components/producerPortfolioEdit/test
  src/@components/producerProfileEdit/DescriptionInfo.tsx
  src/@components/producerProfileEdit/producerProfileEditHeader.tsx
  src/@components/signUp/producerUploadModal.tsx
  src/@components/upload/CategotyInfo.tsx
  src/@components/upload/DescriptionInfo.tsx
  src/@components/upload/DescriptionInput.tsx
  src/@components/upload/FileUploadInfo.tsx
  src/@components/upload/HashtagInfo.tsx
  src/@components/upload/TextLength.tsx
  src/@components/upload/UploadBody.tsx
  src/@components/upload/UploadHeader.tsx
  src/@components/upload/UploadInfoBox.tsx
  src/@components/upload/UploadTitle.tsx
  src/@components/upload/index.tsx
  src/@components/upload/producer/ProducerLayout.tsx
  src/@components/upload/vocal/VocalLayout.tsx
  src/@components/vocalProfileEdit/vocalProfileBody.tsx
  src/@pages/producerPortfolioEditPage
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/uploadPage.tsx
  src/Router.tsx
  src/api/common/client.ts
  src/api/portfolioEdit/getUploadEditInfo.ts
  src/api/upload/producer/editProducerPortfolio.ts
  src/api/upload/producer/editVocalSearching.ts
  src/api/upload/producer/uploadProducer.ts
  src/api/upload/vocal/editVocalPortfolio.ts
  src/api/upload/vocal/uploadVocalPortfolio.ts
  src/core/common/fileType.ts
  src/core/common/path.ts
  src/core/common/queriesKey.ts
  src/core/common/uploadType.ts
  src/core/common/warningMessage.ts
  src/hooks/common/useFileHover.ts
  src/hooks/common/useInputText.ts
  src/hooks/common/useUploadAudioFile.ts
  src/hooks/common/useUploadImageFile.ts
  src/hooks/common/useUploadValue.ts
  src/hooks/queries/upload/upload.ts
  src/hooks/queries/upload/useProducerUpload.ts
  src/hooks/upload/useUploadInitValue.tsx
  src/recoil/upload/uploadData.ts
  src/type/upload/useUploadDataType.ts
  src/utils/common/checkAudioFileType.ts
  src/utils/common/checkFileSize.ts
  src/utils/common/checkFileType.ts
Labels: feat-UI, feat-function, 명헌
