Repository Track-1/client, pull requests merged in 2023-10, with the labels that each got.

#716 Feat#715 common/qa
  src/@components/main/index.tsx
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/portfolio/producerBigPortfolio.tsx
  src/@components/producerProfile/producerPortfolioInform.tsx
  src/@components/producerProfile/producerProfileShadow.tsx
  src/@components/producerProfile/producerVocalSearchingInform.tsx
  src/@components/producerProfile/tracksProfileUploadModal.tsx
  src/@components/signUp/verifyCodeButton.tsx
  src/@components/trackPost/commentWriteProfileContainer.tsx
  src/@components/vocalProfile/index.tsx
  src/@components/vocalProfile/vocalPortfolioInform.tsx
  src/@components/vocalProfile/vocalPortfolioList.tsx
  src/api/common/client.ts
  src/api/path.ts
  src/api/signup/postVerifyCode.ts
  src/hooks/common/useUpdateModal.ts
  src/hooks/queries/user.ts
  src/recoil/common/isUpdateModalOpen.ts
  src/recoil/common/loginUserData.ts
Labels: fix, 지수

#719 Feat#717 common/qa
  src/@components/signUp/conventionCheckBox.tsx
  src/@components/signUp/nickName.tsx
  src/@components/signUp/password.tsx
  src/@components/signUp/passwordConfirm.tsx
  src/@components/signUp/producerUploadModal.tsx
  src/@components/signUp/profileImageContainer.tsx
  src/@components/signUp/signUpBackButton.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/signUp/signupStep.tsx
  src/hooks/common/useUploadImageFile.ts
  src/hooks/queries/user.ts
  src/recoil/signUp/joinUserData.ts
  src/type/signUp/joinUserDataType.ts
Labels: fix, 지수

#720 Feat#713 upload/qa
  package.json
  src/@components/main/mypageButton.tsx
  src/@components/upload/categotyInfo.tsx
  src/@components/upload/descriptionInput.tsx
  src/@components/upload/dropCategory.tsx
  src/@components/upload/fileUploadInfo.tsx
  src/@components/upload/hashtagInfo.tsx
  src/@components/upload/producer/producerLayout.tsx
  src/@components/upload/uploadBody.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/upload/uploadInfoBox.tsx
  src/@components/upload/uploadTitle.tsx
  src/@components/upload/vocal/vocalLayout.tsx
  src/assets/icon/deleteHashtagIc.svg
  src/hooks/common/useDropCategory.ts
  src/hooks/common/useModal.ts
  src/style/globalStyle.ts
Labels: 명헌, code-review

#722 [ feat ] 에러 페이지 구현
  src/@components/error/index.tsx
  src/@pages/errorPage
  src/@pages/errorPage.tsx
  src/Router.tsx
  src/assets/icon/errorPageIc.svg
  src/assets/icon/errorPageMainIc.svg
  src/assets/icon/errorPageTextIc.svg
  src/assets/icon/track1MainLogoIc.svg
  src/assets/index.ts
Labels: 명헌, code-review

#693 Feat#673 login/form
  src/@components/@common/switch.tsx
  src/@components/login/loginForm.tsx
  src/@components/login/switchToggle.tsx
  src/@pages/loginPage.tsx
  src/Router.tsx
  src/assets/icon/loginButtonIc.svg
  src/assets/index.ts
  src/context/switchContext.ts
  src/type/common/switch.ts
Labels: feat-function, 지영, code-review

#724 [ fix ] 라우팅 에러 수정
  src/@pages/loginPage.tsx
  src/Router.tsx
Labels: fix, 지수

#726 [ feat ] 로그인 페이지 백그라운드 삽입
  src/@components/login/loginForm.tsx
  src/@components/login/test
  src/@pages/loginPage
Labels: fix, 지수

#730 [ design ] 모달 위치 수정
  src/@components/trackSearch/uploadButtonModal.tsx
Labels: fix, 지수

#735 [ etc ] 배포를 위한 수정
  public/_redirects
  src/api/common/client.ts
Labels: fix, 지수

#737 [ feat ] 회원가입 페이지 브라우저 뒤로가기 막기
  src/@components/signUp/signUpBackButton.tsx
  src/@components/signUp/signupStep.tsx
Labels: fix, 지수

#738 Feat#733 common/qa
  src/@components/@common/backButton.tsx
  src/@components/@common/filter.tsx
  src/@components/@common/header.tsx
  src/@components/login/loginForm.tsx
  src/@components/main/mypageButton.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeader.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeaderNav.tsx
  src/@pages/loginPage.tsx
  src/@pages/trackSearchPage.tsx
Labels: feat-UI, 명헌, code-review

#745 Feat#712 common/player
  src/@components/@common/player.tsx
  src/@components/login/loginForm.tsx
  src/@components/portfolio/producerBigPortfolio.tsx
  src/@components/portfolio/producerPortfolio.tsx
  src/@components/portfolio/producerSmallPortfolio.tsx
  src/@components/portfolio/vocalBigPortfolio.tsx
  src/@components/portfolio/vocalPortfolio.tsx
  src/@components/portfolio/vocalSmallPortfolio.tsx
  src/@components/producerProfile/ProducerVocalSearchingPortfolio.tsx
  src/@components/producerProfile/index.tsx
  src/@components/producerProfile/producerPortfolioList.tsx
  src/@components/producerProfile/producerVocalSearching.tsx
  src/@components/producerProfile/producerVocalSearchingInform.tsx
  src/@components/trackPost/audioInfo.tsx
  src/@components/trackPost/audioJacketImage.tsx
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/commentInfo.tsx
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/playButton.tsx
  src/@components/trackSearch/trackItem.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalProfile/vocalPortfolioList.tsx
  src/@components/vocalSearch/vocalItem.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalSearchPage.tsx
  src/assets/icon/playerPlayIc.svg
  src/assets/icon/playerQuitIc.svg
  src/assets/icon/playerStopIc.svg
  src/assets/icon/vocalSearchPlayIc.svg
  src/assets/icon/vocalSearchStopIc.svg
  src/assets/index.ts
  src/context/playerContext.tsx
  src/hooks/common/useControlPlayer.ts
  src/hooks/common/usePlay.ts
  src/hooks/common/usePlaySelectedTrack.ts
  src/hooks/queries/comments.ts
  src/type/api.ts
  src/type/comments.ts
  src/type/profile.ts
Labels: feat-function, 지영, code-review

#749 Feat#748 common/hmh qa
  src/@components/@common/hashtag/hashtagInput.tsx
  src/@components/@common/header.tsx
  src/@components/producerProfile/index.tsx
  src/@components/profileEdit/index.tsx
  src/@components/profileEdit/profileHashtagEdit.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeader.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx
  src/@components/upload/hashtagInfo.tsx
  src/@components/upload/uploadBody.tsx
  src/@components/upload/uploadInfoBox.tsx
  src/@pages/trackSearchPage.tsx
  src/api/common/client.ts
  src/hooks/common/useHashtagInput.ts
  src/hooks/queries/mypage.ts
  src/hooks/queries/tracks.ts
Labels: 명헌, code-review

#754 [ feat ] 인앱 브라우저 탈출
  public/index.html
Labels: feat-function, 지수

#760 Feat#748 common/hmh qa
  src/@components/profileEdit/index.tsx
  src/@components/profileEdit/producerProfileEdit/producerImageEdit.tsx
  src/@components/profileEdit/vocalProfileEdit/vocalImageEdit.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx
  src/@components/upload/uploadHeader.tsx
  src/api/tracks.ts
  src/hooks/queries/user.ts
Labels: fix, 명헌, code-review

#757 Feat#756 player/player
  src/@components/@common/backButton.tsx
  src/@components/@common/header.tsx
  src/@components/producerProfile/index.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackSearch/trackItem.tsx
  src/@components/trackSearch/trackSearchHeader/PageTypeNav.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeader.tsx
  src/@components/vocalSearch/vocalItem.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalSearchPage.tsx
  src/context/playerContext.tsx
  src/recoil/common/trackSearchPageType.ts
Labels: fix, 지영

#759 Feat#758 login/qa
  src/@components/login/loginForm.tsx
  src/hooks/queries/user.ts
  src/type/api.ts
Labels: fix, 지영

#762 Fix#755 common/qa
  src/@components/@common/header.tsx
  src/@components/main/index.tsx
  src/@components/producerProfile/producerProfileShadow.tsx
  src/@components/trackPost/audioHashtags.tsx
  src/@components/trackPost/audioInfo.tsx
  src/@components/trackPost/audioTitle.tsx
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/index.tsx
Labels: 지수, qa

#766 Fix#764 portfolio/qa
  src/@components/portfolio/producerPortfolio.tsx
  src/@components/portfolio/vocalPortfolio.tsx
  src/@components/producerProfile/ProducerVocalSearchingPortfolio.tsx
  src/@components/producerProfile/index.tsx
  src/@components/producerProfile/producerProfileShadow.tsx
  src/@components/producerProfile/producerVocalSearchingInform.tsx
  src/@components/producerProfile/viewMoreButton.tsx
  src/@components/producerProfile/vocalSearchingMusicInform.tsx
Labels: 지수, qa

#768 Feat#765 common/private router
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/download.tsx
  src/@pages/trackSearchPage.tsx
  src/Router.tsx
  src/utils/common/privateRouter.tsx
Labels: feat-function, 지수

#771 Feat#767 common/qa
  src/@components/@common/inputContainer.tsx
  src/@components/@common/player.tsx
  src/@components/login/loginForm.tsx
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/index.tsx
  src/@pages/trackPostPage.tsx
  src/assets/icon/passwordEyeIc.svg
  src/assets/index.ts
Labels: fix, 지영

#775 Hotfix#770 qa/jisoo
  src/@components/login/loginForm.tsx
  src/@components/main/index.tsx
  src/@pages/trackSearchPage.tsx
  src/hooks/queries/user.ts
Labels: 지수, qa

#778 Hotfix#773 qa/myeongheon
  src/@components/@common/backButton.tsx
  src/@components/@common/header.tsx
  src/@components/@common/homeLogo.tsx
  src/@components/error/index.tsx
  src/@components/forgotPassword/index.tsx
  src/@components/forgotPassword/userTypeToggle.tsx
  src/@components/main/index.tsx
  src/@components/main/loginButton.tsx
  src/@components/main/mypageButton.tsx
  src/@components/main/profileBox.tsx
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/producerProfile/index.tsx
  src/@components/producerProfile/producerPortfolioInform.tsx
  src/@components/producerProfile/producerVocalSearchingInform.tsx
  src/@components/producerProfile/tracksProfileUploadModal.tsx
  src/@components/profileEdit/index.tsx
  src/@components/profileEdit/vocalProfileEdit/vocalImageEdit.tsx
  src/@components/resetPassword/index.tsx
  src/@components/signUp/producerSuccess.tsx
  src/@components/signUp/producerUploadModal.tsx
  src/@components/signUp/vocalSuccess.tsx
  src/@components/trackPost/download.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/producerProfile.tsx
  src/@components/trackSearch/trackItem.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/upload/categotyInfo.tsx
  src/@components/upload/dropCategory.tsx
  src/@components/upload/index.tsx
  src/@components/upload/producer/producerLayout.tsx
  src/@components/upload/uploadBody.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/upload/vocal/vocalLayout.tsx
  src/@components/uploadEdit/index.tsx
  src/@components/vocalProfile/index.tsx
  src/@components/vocalProfile/vocalPortfolioInform.tsx
  src/@components/vocalSearch/vocalItem.tsx
  src/@pages/loginPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalSearchPage.tsx
  src/api/mypage.ts
  src/assets/icon/headerHomeLogoIc.svg
  src/assets/index.ts
  src/hooks/common/useDropCategory.ts
  src/hooks/common/usePrevPage.ts
  src/hooks/queries/mypage.ts
  src/hooks/queries/profile.ts
  src/hooks/queries/tracks.ts
  src/hooks/queries/user.ts
  src/utils/common/privateRouter.tsx
Labels: feat-function, fix, 명헌, code-review, qa

#780 Hotfix#777 qa/jisoo
  src/@components/main/index.tsx
  src/@components/main/mypageButton.tsx
  src/@components/main/profileBox.tsx
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/portfolio/producerPortfolio.tsx
  src/@components/portfolio/vocalPortfolio.tsx
  src/@components/producerProfile/ProducerVocalSearchingPortfolio.tsx
  src/@components/producerProfile/index.tsx
  src/@components/producerProfile/producerPortfolioInform.tsx
  src/@components/producerProfile/producerProfileShadow.tsx
  src/@components/producerProfile/producerVocalSearching.tsx
  src/@components/producerProfile/producerVocalSearchingInform.tsx
  src/@components/producerProfile/tracksProfileUploadModal.tsx
  src/@components/profile/profileCategory.tsx
  src/@components/profile/profileHashtags.tsx
  src/@components/profileEdit/profileSelectCategoryEdit.tsx
  src/@components/signUp/role.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/signUp/signupStep.tsx
  src/@components/trackPost/audioTitle.tsx
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/commentInfo.tsx
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/producerProfile.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/vocalProfile/index.tsx
  src/@components/vocalProfile/vocalPortfolioInform.tsx
  src/api/mypage.ts
  src/api/path.ts
  src/core/common/categories.ts
  src/hooks/queries/comments.ts
  src/hooks/queries/mypage.ts
  src/hooks/queries/tracks.ts
  src/index.tsx
  src/recoil/trackPost/commentWriteData.ts
Labels: fix, 지수

#779 Hotfix#773 qa/jiyeong
  src/@components/@common/backButton.tsx
  src/@components/@common/filter.tsx
  src/@components/@common/header.tsx
  src/@components/@common/player.tsx
  src/@components/forgotPassword/index.tsx
  src/@components/login/loginForm.tsx
  src/@components/vocalProfile/index.tsx
  src/@components/vocalSearch/vocalItem.tsx
  src/api/path.ts
  src/core/common/routes.ts
  src/core/common/uploadType.ts
  src/type/common/returnType.ts
  src/type/common/routes.ts
  src/type/common/upload.ts
Labels: fix, 지영

#782 [ fix ] 깃 충돌에러 수정
  src/@components/main/profileBox.tsx
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/trackPost/producerProfile.tsx
  src/hooks/queries/mypage.ts
  src/hooks/queries/tracks.ts
Labels: fix, 지수

#786 Fix#785 git/error
  src/@components/@common/backButton.tsx
  src/@components/@common/header.tsx
  src/@components/forgotPassword/index.tsx
  src/@components/main/profileBox.tsx
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/producerProfile.tsx
  src/@components/vocalProfile/index.tsx
  src/hooks/queries/mypage.ts
  src/hooks/queries/tracks.ts
Labels: fix, 지수

#790 [ fix ] 업로드 수정 초기데이터 셋팅값 전달 및 데이터 변수명 수정
  src/@components/trackPost/audioCategory.tsx
  src/@components/trackPost/audioDescription.tsx
  src/@components/trackPost/audioHashtags.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/showMore.tsx
  src/@components/upload/uploadBody.tsx
  src/type/tracks.ts
Labels: fix, code-review, qa

#793 Hotfix#774 qa/myeongheon
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/showMore.tsx
  src/@components/upload/uploadBody.tsx
  src/api/common/client.ts
  src/api/user.ts
  src/hooks/common/useDropCategory.ts
Labels: 명헌, qa

#800 Hotfix#799 qa/jisoo
  src/@components/@common/header.tsx
  src/@components/main/mypageButton.tsx
  src/@components/portfolio/musicInformation.tsx
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/portfolio/producerPortfolio.tsx
  src/@components/portfolio/vocalPortfolio.tsx
  src/@components/producerProfile/ProducerVocalSearchingPortfolio.tsx
  src/@components/producerProfile/vocalSearchingMusicInform.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/assets/icon/discoverChanceIc.svg
  src/assets/index.ts
Labels: fix, 지수

#803 Hotfix#802 qa/jisoo
  src/@components/@common/inputContainer.tsx
  src/@components/main/profileBox.tsx
  src/@components/trackSearch/listTitle.tsx
  src/@components/trackSearch/trackSearchHeader/trackSearchHeaderButton.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/vocalSearch/test
  src/@components/vocalSearch/vocalList.tsx
  src/assets/icon/discoverInspirationIc.svg
  src/assets/index.ts
Labels: 지수, qa

#805 [ fix ] 밑줄 수정
  src/@components/@common/inputContainer.tsx
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/login/loginForm.tsx
Labels: 지수, qa

#807 [ fix ] 모달 위치 수정
  src/@components/login/loginForm.tsx
  src/@pages/loginPage.tsx
Labels: 지수, qa

#809 [ etc ] 오류 수정
  src/@components/producerProfile/tracksProfileUploadModal.tsx
  src/@components/trackPost/commentBox.tsx
  src/@components/vocalSearch/vocalItem.tsx
  src/hooks/common/useUploadAudioFile.ts
  src/hooks/queries/comments.ts
Labels: fix, 지수

#811 Feat#795 renewal/main
  public/index.html
  src/@components/@common/button/customButton.tsx
  src/@components/@common/footer.tsx
  src/@components/main/profileBox.tsx
  src/@components/main/renewal/eventInfo.tsx
  src/@components/main/renewal/eventSection.tsx
  src/@components/main/renewal/home.tsx
  src/@components/main/renewal/loginBtn.tsx
  src/@components/main/renewal/mainBanner.tsx
  src/@components/main/renewal/mainNav.tsx
  src/@components/main/renewal/recentInfoSection.tsx
  src/@components/main/renewal/recentTrackInfo.tsx
  src/@components/main/renewal/recentTrackList.tsx
  src/@components/main/renewal/recentVocalItem.tsx
  src/@components/main/renewal/recentVocalList.tsx
  src/@pages/homePage.tsx
  src/Router.tsx
  src/api/path.ts
  src/api/tracks.ts
  src/api/vocals.ts
  src/assets/icon/mainLogoWhiteIc.svg
  src/assets/icon/pauseIc.svg
  src/assets/icon/playIc.svg
  src/assets/image/mainBannerBackgroundImg.png
  src/assets/index.ts
  src/hooks/queries/tracks.ts
  src/hooks/queries/vocals.ts
  src/style/theme.ts
  src/type/api.ts
Labels: feat-UI, feat-function, 명헌, code-review

#814 Feat#812 portfolio/contact
  src/@components/profile/index.tsx
  src/@components/upload/descriptionInput.tsx
Labels: feat-function, 지수

#815 Feat#810 renewal/event page
  src/@components/admin/adminHeader.tsx
  src/@components/admin/event/eventUpload.tsx
  src/@components/admin/index.tsx
  src/@components/event/eventDetail.tsx
  src/@components/event/eventList.tsx
  src/@components/event/hotEvent.tsx
  src/@components/event/index.tsx
  src/@components/main/renewal/eventInfo.tsx
  src/@components/main/renewal/eventSection.tsx
  src/@components/main/renewal/home.tsx
  src/@components/main/renewal/loginBtn.tsx
  src/@components/main/renewal/mainHeader.tsx
  src/@components/main/renewal/mainNav.tsx
  src/@components/main/renewal/profileBox.tsx
  src/@components/main/renewal/recentInfoSection.tsx
  src/@components/main/renewal/recentTrackItem.tsx
  src/@components/main/renewal/recentTrackList.tsx
  src/@components/main/renewal/recentVocalItem.tsx
  src/@components/producerProfile/tracksProfileUploadModal.tsx
  src/@components/upload/index.tsx
  src/@pages/adminPage.tsx
  src/@pages/eventPage.tsx
  src/Router.tsx
  src/api/admin/event.ts
  src/api/path.ts
  src/api/user.ts
  src/assets/icon/eventBackBtnIc.svg
  src/assets/icon/eventToggleIc.svg
  src/assets/icon/scrollTopBtnIc.svg
  src/assets/index.ts
  src/core/common/queriesKey.ts
  src/hooks/queries/admin/event.ts
  src/hooks/queries/user.ts
  src/style/theme.ts
  src/type/api.ts
  src/type/event.ts
Labels: feat-UI, feat-function, 명헌, code-review
