Repository Track-1/client, pull requests merged in 2023-09, with the labels that each got.

#667 Feat#666 common/mobile alert n manifest
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/@components/trackPost/userComment.tsx
  src/@pages/mobileAlertPage.tsx
  src/App.tsx
  src/Router.tsx
  yarn.lock
Labels: feat-function, 지수

#662 Feat#644 common/api
  src/api/comments.ts
  src/api/mypage.ts
  src/api/path.ts
  src/api/profile.ts
  src/api/tracks.ts
  src/api/user.ts
  src/api/vocals.ts
  src/core/common/queriesKey.ts
  src/hooks/queries/comments.ts
  src/hooks/queries/mypage.ts
  src/hooks/queries/profile.ts
  src/hooks/queries/tracks.ts
  src/hooks/queries/user.ts
  src/hooks/queries/vocals.ts
  src/type/api.ts
  src/type/comments.ts
  src/type/mypage.ts
  src/type/profile.ts
  src/type/tracks.ts
  src/type/user.ts
  src/type/vocals.ts
Labels: feat-function, 지영

#655 Feat#654 track post/comment open
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/index.tsx
  src/assets/icon/commentBtnIc.svg
  src/assets/index.ts
Labels: feat-function, 지수

#653 Feat#652 track post/comment delete
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/commentInfo.tsx
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/index.tsx
  src/api/trackPost/deleteTrackComment.ts
  src/assets/icon/commentBtnIc.svg
  src/assets/index.ts
Labels: refactor, 지수, code-review

#649 Feat#646 track post/comment post
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/commentContentLength.tsx
  src/@components/trackPost/commentFileInput.tsx
  src/@components/trackPost/commentInfo.tsx
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/commentTextInput.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/commentWriteLayout.tsx
  src/@components/trackPost/commentWriteProfileContainer.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/index.tsx
  src/api/trackPost/deleteComment.ts
  src/api/trackPost/deleteTrackComment.ts
  src/api/trackPost/postComment.ts
  src/api/trackPost/updateComment.ts
  src/assets/icon/addCommentIc.svg
  src/assets/icon/closedAddCommentIc.svg
  src/assets/icon/commentBtnIc.svg
  src/assets/icon/commentUpldatCompleteIc.svg
  src/assets/icon/fileUploadButtonIc.svg
  src/assets/icon/quitIc.svg
  src/assets/index.ts
  src/hooks/common/useModal.ts
  src/hooks/common/useUploadAudioFile.ts
  src/recoil/trackPost/commentWriteData.ts
  src/type/trackPost/commentDataType.ts
  src/type/trackPost/commentInputProps.ts
  src/type/trackPost/commentIsUpdateProp.ts
  src/type/trackPost/commentType.ts
  src/utils/common/checkIsLogined.ts
Labels: refactor, 지수, code-review

#645 Feat#641 track post/comment get
  src/@components/trackPost/audioCategory.tsx
  src/@components/trackPost/audioDescription.tsx
  src/@components/trackPost/audioHashtags.tsx
  src/@components/trackPost/audioJacketImage.tsx
  src/@components/trackPost/audioTitle.tsx
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/commentContentLength.tsx
  src/@components/trackPost/commentFileInput.tsx
  src/@components/trackPost/commentInfo.tsx
  src/@components/trackPost/commentLayout.tsx
  src/@components/trackPost/commentProfileEventBox.tsx
  src/@components/trackPost/commentTextInput.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/commentWriteLayout.tsx
  src/@components/trackPost/commentWriteProfileContainer.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/download.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/index.tsx
  src/@components/trackPost/producerProfile.tsx
  src/@components/trackPost/showMore.tsx
  src/api/trackPost/deleteComment.ts
  src/api/trackPost/deleteTrackComment.ts
  src/api/trackPost/getComment.ts
  src/api/trackPost/postComment.ts
  src/api/trackPost/updateComment.ts
  src/assets/icon/addCommentIc.svg
  src/assets/icon/closeCommentsBtnIc.svg
  src/assets/icon/closedAddCommentIc.svg
  src/assets/icon/commentBtnIc.svg
  src/assets/icon/commentUpldatCompleteIc.svg
  src/assets/icon/ellipsisIc.svg
  src/assets/icon/fileUploadButtonIc.svg
  src/assets/icon/pauseButtonIc.svg
  src/assets/icon/playButtonIc.svg
  src/assets/icon/quitIc.svg
  src/assets/index.ts
  src/core/common/queriesKey.ts
  src/hooks/common/useModal.ts
  src/hooks/common/useUploadAudioFile.ts
  src/hooks/trackPost/useGetComment.ts
  src/hooks/trackPost/useGetTrackInfo.ts
  src/recoil/common/playMusic.ts
  src/recoil/trackPost/clickedTrackId.ts
  src/recoil/trackPost/commentWriteData.ts
  src/type/trackPost/commentDataType.ts
  src/type/trackPost/commentInputProps.ts
  src/type/trackPost/commentIsUpdateProp.ts
  src/type/trackPost/commentType.ts
  src/utils/common/checkHover.ts
  src/utils/common/checkIsLogined.ts
Labels: refactor, 지수, code-review

#678 [ fix ] useAudioFIle 커스텀훅 반환 변수 변경으로 인한 에러 해결
  src/@components/trackPost/commentFileInput.tsx
  src/hooks/common/useUploadAudioFile.ts
Labels: fix, 명헌

#665 Feat#664 forgot password/UI
  src/@components/@common/backButton.tsx
  src/@components/@common/button/standardButton.tsx
  src/@components/@common/header.tsx
  src/@components/@common/passwordContainer.tsx
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/forgotPassword/index.tsx
  src/@components/forgotPassword/userTypeToggle.tsx
  src/@components/main/loginButton.tsx
  src/@components/main/test
  src/@pages/forgotPasswordPage.tsx
  src/Router.tsx
  src/assets/icon/defaultToggleIc.svg
  src/assets/icon/homeLogoIc.svg
  src/assets/icon/producerTypeToggleIc.svg
  src/assets/icon/sloganIc.svg
  src/assets/image/backgroundImg.png
  src/assets/index.ts
  src/hooks/forgotPassword/useForgotPasswordData.ts
  src/style/theme.ts
Labels: feat-UI, feat-function, refactor, 명헌, code-review

#686 Feat#675 main/UI
  src/@components/@common/conventionModal.tsx
  src/@components/main/ads.tsx
  src/@components/main/index.tsx
  src/@components/main/loginButton.tsx
  src/@pages/mainPage
  src/@pages/mainPage.tsx
  src/Router.tsx
  src/assets/icon/mainAdsIc.svg
  src/assets/icon/mainTracksTextIc.svg
  src/assets/icon/mainVocalsTextIc.svg
  src/assets/image/adsImg.png
  src/assets/image/hoverTracksImg.png
  src/assets/image/hoverVocalsImg.png
  src/assets/image/mainBackgroundImg.png
  src/assets/image/mainPageBackgroundImg.png
  src/assets/image/mainSloganImg.png
  src/assets/index.ts
  src/core/trackSearch/categorySelectedCheck.ts
  src/hooks/common/useConventionModal.ts
  src/recoil/common/categorySelect.ts
Labels: refactor, 지수

#683 Feat#672 reset password/page
  src/@components/@common/passwordContainer.tsx
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/resetPassword/index.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@components/resetPassword/test
  src/@components/signUp/Input.tsx
  src/@components/signUp/emailPassword.tsx
  src/@components/signUp/password.tsx
  src/@components/signUp/passwordConfirm.tsx
  src/@pages/resetPasswordPage.tsx
  src/Router.tsx
  src/api/user.ts
  src/core/common/queriesKey.ts
  src/hooks/queries/user.ts
  src/type/signUp/inputProps.ts
Labels: feat-UI, 명헌, code-review

#684 Feat#682 forgot password/api
  src/@components/@common/button/standardButton.tsx
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/signUp/Input.tsx
  src/@components/upload/CategotyInfo.tsx
  src/@components/upload/DescriptionInfo.tsx
  src/@components/upload/FileUploadInfo.tsx
  src/@components/upload/HashtagInfo.tsx
  src/@components/upload/uploadInfoBox.tsx
  src/assets/icon/requestBlackTextIc.svg
  src/assets/icon/requestWhiteTextIc.svg
  src/assets/icon/resendTextIc.svg
  src/assets/index.ts
  src/core/signUp/errorMessage.ts
  src/utils/signUp/inputStyle.ts
Labels: feat-function, 명헌

#685 Feat#660 profile edit/change custom hook pattern
  src/@components/@common/hashtag/hashtagInput.tsx
  src/@components/@common/hashtag/hashtagWarning.tsx
  src/@components/@common/hashtag/hashtagsEdit.tsx
  src/@components/@common/inputContainer.tsx
  src/@components/producerProfileEdit/DescriptionInfo.tsx
  src/@components/producerProfileEdit/index.tsx
  src/@components/producerProfileEdit/producerImageEdit.tsx
  src/@components/producerProfileEdit/producerProfileBody.tsx
  src/@components/producerProfileEdit/producerProfileEditHeader.tsx
  src/@components/profileEdit/index.tsx
  src/@components/profileEdit/producerProfileEdit/producerImageEdit.tsx
  src/@components/profileEdit/profileContactEdit.tsx
  src/@components/profileEdit/profileDescriptionEdit.tsx
  src/@components/profileEdit/profileHashtagEdit.tsx
  src/@components/profileEdit/profileNameEdit.tsx
  src/@components/profileEdit/profileSelectCategoryEdit.tsx
  src/@components/profileEdit/profileTitleInput.tsx
  src/@components/profileEdit/vocalProfileEdit/vocalImageEdit.tsx
  src/@components/profileEdit/vocalProfileEdit/vocalSleeper.tsx
  src/@components/signUp/Input.tsx
  src/@components/signUp/inputTitle.tsx
  src/@components/upload/DescriptionInfo.tsx
  src/@components/upload/DescriptionInput.tsx
  src/@components/upload/HashtagInfo.tsx
  src/@components/upload/UploadBody.tsx
  src/@components/upload/producer/ProducerLayout.tsx
  src/@components/vocalProfileEdit/index.tsx
  src/@components/vocalProfileEdit/vocalImageEdit.tsx
  src/@components/vocalProfileEdit/vocalProfileBody.tsx
  src/@components/vocalProfileEdit/vocalSleeper.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/assets/icon/uploadActiveSaveButtonIc.svg
  src/assets/icon/uploadUnActiveSaveButtonIc.svg
  src/assets/image/uploadProducerDefaultImg.png
  src/assets/index.ts
  src/core/common/textLimit.ts
  src/hooks/common/useHashtagInput.ts
  src/hooks/common/useUploadImageFile.ts
  src/hooks/common/useUploadValue.ts
  src/hooks/producerProfileEdit/test
  src/hooks/producerProfileEdit/useSelectCategories.ts
  src/type/common/textLimitType.ts
  src/type/signUp/nickNameProp.ts
Labels: refactor, 명헌, code-review

#691 [ feat ] profileEdit api 연결
  src/@components/profileEdit/index.tsx
  src/@components/profileEdit/producerProfileEdit/producerImageEdit.tsx
  src/@components/profileEdit/vocalProfileEdit/vocalImageEdit.tsx
  src/api/profile.ts
  src/hooks/queries/profile.ts
  src/type/producerProfileEdit/test
  src/type/profile.ts
  src/type/vocalProfileEdit/test
Labels: feat-function, 명헌, code-review

#695 Feat#694 track search/api
  src/@components/trackSearch/listTitle.tsx
  src/@components/trackSearch/trackItem.tsx
  src/@components/trackSearch/trackList.tsx
  src/assets/icon/trackSearchSlogunIc.svg
  src/assets/index.ts
  src/hooks/common/useInfiniteScroll.ts
  src/hooks/queries/tracks.ts
  src/type/api.ts
  src/type/tracks.ts
Labels: feat-function, 지영, code-review

#688 Feat#687 profile/common
  src/@components/producerProfile/index.tsx
  src/@components/producerProfile/test
  src/@components/profile/empty.tsx
  src/@components/profile/hashtag.tsx
  src/@components/profile/index.tsx
  src/@components/profile/producerProfileImage.tsx
  src/@components/profile/profileCategory.tsx
  src/@components/profile/profileDescription.tsx
  src/@components/profile/profileHashtags.tsx
  src/@components/profile/vocalProfileImage.tsx
  src/@components/vocalProfile/index.tsx
  src/@components/vocalProfile/test
  src/@pages/producerProfilePage
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalProfilePage
  src/@pages/vocalProfilePage.tsx
  src/Router.tsx
  src/api/common/client.ts
  src/api/path.ts
  src/api/profile.ts
  src/assets/icon/profileEditBtnIc.svg
  src/assets/icon/sleeperAccountIc.svg
  src/assets/index.ts
  src/core/common/categories.ts
  src/hooks/producerProfile/test
  src/hooks/producerProfile/useGetProducerProfile.ts
  src/hooks/vocalProfile/test
  src/hooks/vocalProfile/useGetVocalProfile.ts
  src/type/profile.ts
Labels: refactor, 지수, code-review

#697 Feat#696 vocal search/api
  src/@components/@common/filter.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalSearch/vocalItem.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/hooks/common/useInfiniteScroll.ts
  src/hooks/queries/tracks.ts
  src/hooks/queries/vocals.ts
  src/type/api.ts
  src/type/vocals.ts
Labels: feat-function, fix, 지영, code-review

#700 Feat#687 profile/common
  src/@components/portfolio/musicInformation.tsx
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/portfolio/producerBigPortfolio.tsx
  src/@components/portfolio/producerSmallPortfolio.tsx
  src/@components/portfolio/vocalBigPortfolio.tsx
  src/@components/portfolio/vocalSmallPortfolio.tsx
  src/@components/producerProfile/index.tsx
  src/@components/producerProfile/producerPortfolioInform.tsx
  src/@components/producerProfile/producerPortfolioList.tsx
  src/@components/producerProfile/producerProfileShadow.tsx
  src/@components/producerProfile/producerVocalSearching.tsx
  src/@components/producerProfile/producerVocalSearchingInform.tsx
  src/@components/producerProfile/tracksProfileUploadModal.tsx
  src/@components/producerProfile/viewMoreButton.tsx
  src/@components/profile/producerProfileImage.tsx
  src/@components/profile/vocalProfileImage.tsx
  src/@components/vocalProfile/index.tsx
  src/@components/vocalProfile/vocalPortfolioInform.tsx
  src/@components/vocalProfile/vocalPortfolioList.tsx
  src/@components/vocalProfile/vocalProfileShadow.tsx
  src/api/common/client.ts
  src/api/profile.ts
  src/assets/icon/PortfolioIc.svg
  src/assets/icon/PortfolioTextIc.svg
  src/assets/icon/VocalSearchingIc.svg
  src/assets/icon/VocalSearchingTextIc.svg
  src/assets/icon/pencilUpdateIc.svg
  src/assets/icon/portfolioPauseIc.svg
  src/assets/icon/portfolioPlayIc.svg
  src/assets/icon/producerProfileShadowIc.svg
  src/assets/icon/producerProfileTitleTextIc.svg
  src/assets/icon/producerProfileUploadeModalIc.svg
  src/assets/icon/producerVocalSearchingArrowIc.svg
  src/assets/icon/producerVocalSearchingViewMoreTextIc.svg
  src/assets/icon/rightArrorIc.svg
  src/assets/icon/setIsTitleIc.svg
  src/assets/icon/trashDeleteIc.svg
  src/assets/icon/uploadButtonIc.svg
  src/assets/icon/vocalPortfolioTitleTextIc.svg
  src/assets/icon/vocalProfileShadowIc.svg
  src/assets/image/producerEmptyProfileImg.png
  src/assets/image/vocalEmptyProfileImg.png
  src/assets/index.ts
  src/hooks/common/useModal.ts
  src/hooks/producerProfile/test
  src/hooks/producerProfile/useGetProducerProfile.ts
  src/hooks/queries/mypage.ts
  src/hooks/vocalProfile/test
  src/hooks/vocalProfile/useGetVocalProfile.ts
  src/recoil/common/profile.ts
  src/type/api.ts
  src/type/profile.ts
  src/type/vocals.ts
Labels: feat-UI, feat-function, 지수, code-review

#702 Feat#701 portfolio/qa
  src/@components/portfolio/portfolioUpdateModal.tsx
  src/@components/producerProfile/index.tsx
  src/@components/producerProfile/producerPortfolioInform.tsx
  src/@components/producerProfile/producerProfileShadow.tsx
  src/@components/producerProfile/producerVocalSearching.tsx
  src/@components/producerProfile/producerVocalSearchingInform.tsx
  src/@components/producerProfile/tracksProfileUploadModal.tsx
  src/@components/vocalProfile/vocalPortfolioInform.tsx
  src/api/common/client.ts
  src/api/mypage.ts
  src/hooks/common/useModal.ts
  src/hooks/queries/mypage.ts
Labels: fix, 지수

#704 Feat#703 signup/fix api
  src/@components/profileEdit/index.tsx
  src/@components/profileEdit/profileDescriptionEdit.tsx
  src/@components/signUp/email.tsx
  src/@components/signUp/sendCodeButton.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/signUp/signupSeccess.tsx
  src/@components/signUp/signupStep.tsx
  src/@components/signUp/stepFooter.tsx
  src/@components/signUp/verifyCode.tsx
  src/@components/upload/categotyInfo.tsx
  src/@components/upload/descriptionInfo.tsx
  src/@components/upload/descriptionInput.tsx
  src/@components/upload/fileUploadInfo.tsx
  src/@components/upload/hashtagInfo.tsx
  src/@components/upload/uploadBody.tsx
  src/@pages/signupProfilePage.tsx
  src/@pages/signupStepPage.tsx
  src/@pages/signupSuccessPage.tsx
  src/api/profile.ts
  src/api/user.ts
  src/assets/icon/signupProfileBackgroundIc.svg
  src/assets/icon/signupProfileCompleteTextIc.svg
  src/assets/icon/signupProfileSkipIc.svg
  src/assets/index.ts
  src/core/common/textLimit.ts
  src/hooks/queries/profile.ts
  src/hooks/queries/user.ts
  src/type/api.ts
  src/type/user.ts
Labels: refactor, 지수

#706 Feat#705 track post/fix api
  src/@components/trackPost/audioCategory.tsx
  src/@components/trackPost/audioDescription.tsx
  src/@components/trackPost/audioHashtags.tsx
  src/@components/trackPost/audioJacketImage.tsx
  src/@components/trackPost/audioTitle.tsx
  src/@components/trackPost/commentBox.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/comments.tsx
  src/@components/trackPost/download.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/producerProfile.tsx
  src/api/comments.ts
  src/api/tracks.ts
  src/hooks/queries/comments.ts
  src/hooks/queries/tracks.ts
  src/recoil/common/loginUserData.ts
  src/type/api.ts
  src/type/comments.ts
Labels: refactor, 지수

#708 [ feat ] 헤더 로그인 버튼 컴포넌트 구현
  src/@components/main/index.tsx
  src/@components/main/loginButton.tsx
  src/@components/main/mypageButton.tsx
  src/@components/main/profileBox.tsx
  src/assets/icon/loginIc.svg
  src/assets/icon/logoutIc.svg
  src/assets/icon/producerTextIc.svg
  src/assets/icon/signupIc.svg
  src/assets/icon/vocalTextIc.svg
  src/assets/index.ts
Labels: feat-function, 명헌, code-review

#709 Feat#699 upload/category
  src/@components/upload/categotyInfo.tsx
  src/@components/upload/descriptionInfo.tsx
  src/@components/upload/dropCategory.tsx
  src/@components/upload/fileUploadInfo.tsx
  src/@components/upload/hashtagInfo.tsx
  src/@components/upload/uploadBody.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/upload/uploadTitle.tsx
  src/api/tracks.ts
  src/assets/icon/checkCategoryIc.svg
  src/assets/index.ts
  src/hooks/common/useDropCategory.ts
  src/hooks/queries/mypage.ts
  src/hooks/queries/tracks.ts
Labels: feat-UI, 명헌, code-review

#710 Feat#698 common/filtering data
  src/@components/@common/checkBox.tsx
  src/@components/@common/filter.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/api/tracks.ts
  src/api/vocals.ts
  src/assets/icon/trackSearchingFalseIc.svg
  src/assets/icon/trackSearchingTrueIc.svg
  src/assets/index.ts
  src/core/common/queriesKey.ts
  src/hooks/queries/vocals.ts
  src/type/common/checkbox.ts
  src/type/tracks.ts
Labels: feat-function, 지영, code-review

#711 [ feat ] 로그아웃 api 기능 구현 및 프로필버튼 구현
  src/@components/main/loginButton.tsx
  src/@components/main/mypageButton.tsx
  src/@components/main/profileBox.tsx
  src/@components/upload/categotyInfo.tsx
  src/hooks/queries/mypage.ts
  src/hooks/queries/user.ts
Labels: feat-UI, 명헌, code-review
