Repository Track-1/client, pull requests merged in 2023-03, with the labels that each got.

#180 Feat#179 sign up/role
  src/@components/@common/backButton.tsx
  src/@components/signUp/continueButton.tsx
  src/@components/signUp/signUpStepRenderer.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupRole.tsx
  src/@components/signUp/signupStepHeader.tsx
  src/@pages/signUpPage.tsx
  src/Router.tsx
  src/assets/icon/loginHereMessageIc.svg
  src/assets/icon/signBackgroundIc.svg
  src/assets/icon/signBgLogoIc.svg
  src/assets/icon/signUpContinueButtonIc.svg
  src/assets/icon/signUpSelectRoleTitleIc.svg
  src/assets/icon/signUpStep1Ic.svg
  src/assets/icon/signUpStep2Ic.svg
  src/assets/icon/signUpStep3Ic.svg
  src/assets/icon/signUpStepBlanckIc.svg
  src/assets/icon/signWelcomeIc.svg
  src/assets/icon/signupNotSelectedProducerIc.svg
  src/assets/icon/signupNotSelectedVocalIc.svg
  src/assets/icon/signupSelectedProducerIc.svg
  src/assets/icon/signupSelectedVocalIc.svg
  src/assets/index.ts
  src/core/signUp/signupStepType.ts
  src/type/signUpStepTypes.ts
  src/utils/signUp/checkMessageType.ts
  src/utils/signUp/stepType.ts
Labels: feat-UI, feat-function, 지수

#186 Feat#181 sign up/email password UI
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/continueButton.tsx
  src/@components/signUp/sendCodeButton.tsx
  src/@components/signUp/signUpStepRenderer.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupRole.tsx
  src/@components/signUp/verifyButton.tsx
  src/@pages/signUpPage.tsx
  src/assets/icon/confirmPasswordTextIc.svg
  src/assets/icon/createAPasswordForYourAccountTitleIc.svg
  src/assets/icon/signUpBackArrowIc.svg
  src/assets/icon/signUpEmailTitleIc.svg
  src/assets/icon/signUpErrorIc.svg
  src/assets/icon/signUpEyeIc.svg
  src/assets/icon/signUpEyeXIc.svg
  src/assets/icon/signUpPasswordIc.svg
  src/assets/icon/signUpVerifyButtonIc.svg
  src/assets/icon/signupResendButtonIc.svg
  src/assets/icon/signupSendcodeTextIc.svg
  src/assets/icon/signupVerifyIc.svg
  src/assets/icon/verificationCodeTextIc.svg
  src/assets/icon/weSentYouACodeTextIc.svg
  src/assets/icon/what'sYourEmailIc.svg
  src/assets/index.ts
  src/core/api/signUp.ts
  src/core/signUp/continueType.ts
  src/core/signUp/passwordConfirm.ts
  src/core/signUp/signupStepType.ts
  src/core/userInfoErrorMessage/emailInvalidMessage.ts
  src/core/userInfoErrorMessage/passwordInvalidMessage.ts
  src/core/userInfoErrorMessage/verificationCodeInvalidMessage.ts
  src/style/theme.ts
  src/type/signUpStepTypes.ts
  src/utils/errorMessage/checkEmailForm.ts
  src/utils/errorMessage/checkPasswordForm.ts
  src/utils/errorMessage/setInputStyle.ts
  src/utils/signUp/checkMessageType.ts
  src/utils/signUp/stepType.ts
Labels: feat-UI, feat-function, 지수

#190 Feat#187 sign up/nickname convention UI
  src/@components/@common/conventionModal.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/continueButton.tsx
  src/@components/signUp/conventionCheckBox.tsx
  src/@components/signUp/signUpStepRenderer.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/signUp/signupRole.tsx
  src/@pages/signUpPage.tsx
  src/assets/icon/conventionBlanckBoxIc.svg
  src/assets/icon/conventionFullBoxIc.svg
  src/assets/icon/signUpBackgroundIc.svg
  src/assets/icon/signUpChangeImageIc.svg
  src/assets/icon/signUpCompleteButtonIc.svg
  src/assets/icon/signUpModalXIc.svg
  src/assets/icon/signUpSkipButtonIc.svg
  src/assets/icon/signUpUploadImageIc.svg
  src/assets/icon/whatsYourNameTextIc.svg
  src/assets/index.ts
  src/core/convention/conventionType.ts
  src/core/convention/marketingInformationAgreePolicy.ts
  src/core/convention/personalInformationProcessingPolicy.ts
  src/core/convention/usingSitePolicy.ts
  src/core/signUp/continueType.ts
  src/core/signUp/conventionSelectedCheck.ts
  src/core/signUp/signupStepType.ts
  src/core/userInfoErrorMessage/color.ts
  src/core/userInfoErrorMessage/nicknameMessage.ts
  src/style/theme.ts
  src/type/conventionChecksType.ts
  src/utils/convention/checkConventionType.ts
  src/utils/errorMessage/checkNicknameForm.ts
  src/utils/errorMessage/setInputStyle.ts
  src/utils/signUp/checkMessageType.ts
Labels: feat-UI, feat-function, 지수

#192 Feat#183 profile/left section
  src/@components/@common/profileEditInfo.tsx
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@components/profileEdit/profileEditHeader.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@pages/profileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/Router.tsx
  src/assets/icon/profileEditActiveButtonIc.svg
  src/assets/icon/profileEditCategoryIc.svg
  src/assets/icon/profileEditCheckIc.svg
  src/assets/icon/profileEditContactIc.svg
  src/assets/icon/profileEditDescriptionIc.svg
  src/assets/icon/profileEditHashtagIc.svg
  src/assets/icon/profileEditSaveButtonActiveIc.svg
  src/assets/icon/profileEditSaveButtonIc.svg
  src/assets/icon/profileEditSleepAcountTextIc.svg
  src/assets/icon/profileEditSleepAcountTitleIc.svg
  src/assets/icon/profileEditSleeperButtonIc.svg
  src/assets/icon/profileEditWarningIc.svg
  src/assets/image/profileEditUploadDefaultImg.png
  src/assets/image/profileEditVocalDefaultImg.png
  src/assets/index.ts
  src/core/api/common/axios.ts
  src/core/api/producerProfile.ts
  src/core/api/trackSearch.ts
  src/core/api/vocalProfile.ts
  src/core/constants/categories.ts
  src/core/editProfile/editData.ts
  src/style/theme.ts
  src/type/CategoryChecksType.ts
  src/type/editDataType.ts
  src/type/test.ts
Labels: feat-UI, feat-function, 지영

#194 Feat#193 main/login
  src/@components/@common/mainHeader.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@pages/mainPage.tsx
  src/assets/icon/loginIc.svg
  src/assets/icon/mainInfoProducerIc.svg
  src/assets/icon/mainInfoVocalIc.svg
  src/assets/icon/mainLogoutIc.svg
  src/assets/icon/signupIc.svg
  src/assets/index.ts
  src/recoil/main.ts
Labels: feat-UI, feat-function, 지영

#195 Feat#191 sign up/profile UI
  src/@components/@common/conventionModal.tsx
  src/@components/signUp/conventionCheckBox.tsx
  src/@components/signUp/signUpBackButton.tsx
  src/@components/signUp/signUpStepRenderer.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupRole.tsx
  src/@components/signUp/signupStepHeader.tsx
  src/@components/signUp/signupSuccess.tsx
  src/@pages/signUpPage.tsx
  src/Router.tsx
  src/assets/icon/moveTouploadPortfolioButtonIc.svg
  src/assets/icon/moveTouploadVocalSearchingButtonIc.svg
  src/assets/icon/signUpGetStartedButtonIc.svg
  src/assets/icon/signUpProducerButtonIc.svg
  src/assets/icon/signUpProducerQIc.svg
  src/assets/icon/signUpSuccessBackgroundIc.svg
  src/assets/icon/signUpVocalButtonIc.svg
  src/assets/icon/signUpVocalQIc.svg
  src/assets/index.ts
  src/core/signUp/signupStepType.ts
  src/recoil/conventionModal.ts
  src/recoil/main.ts
  src/utils/common/userType.ts
  src/utils/signUp/checkSignUpStep.ts
  src/utils/signUp/stepType.ts
Labels: feat-UI, feat-function, 지수

#199 Feat#197 common/footer
  src/@components/@common/footer.tsx
  src/@components/@common/mainHeader.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@pages/mainPage.tsx
  src/assets/icon/facebookLogoIc.svg
  src/assets/icon/instagramLogoIc.svg
  src/assets/index.ts
  src/style/theme.ts
Labels: feat-UI, 지수

#201 Feat#196 sign up/save data
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/signUp/sendCodeButton.tsx
  src/@components/signUp/signUpStepRenderer.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/signUp/signupStepHeader.tsx
  src/@components/signUp/verifyButton.tsx
  src/@pages/signUpPage.tsx
  src/assets/icon/signupVocalProfileImgIc.svg
  src/assets/index.ts
  src/core/api/signUp.ts
  src/type/signUpStepTypes.ts
  src/utils/signUp/checkSignUpStep.ts
  src/utils/uploadPage/uploadImage.ts
Labels: feat-UI, feat-function, 지수

#203 Feat#182 login/UI
  src/@components/login/loginInput.tsx
Labels: feat-UI, feat-function, 명헌

#208 Feat#207 sign up/detail
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/conventionCheckBox.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/signUp/signUpStepRenderer.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/signUp/signupProfile.tsx
  src/@pages/signUpPage.tsx
  src/assets/icon/signUpChangeImgIc.svg
  src/assets/icon/signUpVocalChangePhotoIc.svg
  src/assets/icon/signupProfileCompleteIc.svg
  src/assets/index.ts
  src/core/api/profile.ts
  src/type/signUpStepTypes.ts
Labels: feat-function, 지수

#214 Feat#213 qa/detail
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/mainHeader.tsx
  src/@components/login/loginInput.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/trackPost/commentHeader.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/loginPage.tsx
  src/@pages/mainPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/icon/closedAddCommentIc.svg
  src/assets/icon/ifyourareanewuserIc.svg
  src/assets/icon/loginEmailIc.svg
  src/assets/icon/loginPasswordIc.svg
  src/assets/icon/loginTitleIc.svg
  src/assets/icon/loginforgotpasswordIc.svg
  src/assets/icon/signuphereIc.svg
  src/assets/icon/trackheadersloganIc.svg
  src/assets/index.ts
  src/core/api/signUp.ts
  src/core/api/trackPost.ts
  src/core/api/trackSearch.ts
  src/core/api/vocalSearch.ts
  src/recoil/loginUserData.ts
Labels: feat-function, 지수

#212 Feat#209 main/detail
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/mainHeader.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/login/loginInput.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/conventionCheckBox.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/signUp/signUpStepRenderer.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/trackPost/commentHeader.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/loginPage.tsx
  src/@pages/mainPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/icon/closedAddCommentIc.svg
  src/assets/icon/ifyourareanewuserIc.svg
  src/assets/icon/loginEmailIc.svg
  src/assets/icon/loginPasswordIc.svg
  src/assets/icon/loginTitleIc.svg
  src/assets/icon/loginforgotpasswordIc.svg
  src/assets/icon/signuphereIc.svg
  src/assets/icon/trackheadersloganIc.svg
  src/assets/index.ts
  src/core/api/delete.ts
  src/core/api/login.ts
  src/core/api/logout.ts
  src/core/api/producerProfile.ts
  src/core/api/profile.ts
  src/core/api/signUp.ts
  src/core/api/trackPost.ts
  src/core/api/trackSearch.ts
  src/core/api/vocalProfile.ts
  src/core/api/vocalSearch.ts
  src/recoil/loginUserData.ts
  src/type/producerProfile.ts
  src/type/profilePropsType.ts
  src/type/userPropsType.ts
  src/type/vocalProfile.ts
Labels: feat-function, 지수

#215 Feat#174 common/api delete
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/userComment.tsx
  src/core/api/delete.ts
  src/core/api/login.ts
  src/core/api/profile.ts
  src/core/api/trackPost.ts
Labels: feat-function, fix, 명헌

#217 Feat#189 reset password/UI api
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@pages/resetPasswordPage.tsx
  src/Router.tsx
  src/assets/icon/defaultSaveBtnIc.svg
  src/assets/icon/hiddenPasswordIc.svg
  src/assets/icon/inputSuccessIc.svg
  src/assets/icon/inputWarningIc.svg
  src/assets/icon/resetPasswordTitleIc.svg
  src/assets/icon/saveBtnIc.svg
  src/assets/icon/showPasswordIc.svg
  src/assets/index.ts
  src/core/api/resetPassword.ts
  src/core/api/validateResetPasswordToken.ts
  src/core/userInfoErrorMessage/passwordInvalidMessage.ts
  src/utils/errorMessage/checkPasswordForm.ts
Labels: feat-UI, feat-function, 명헌

#216 Feat#188 forgot password/UI api
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@pages/forgotPasswordPage.tsx
  src/Router.tsx
  src/assets/icon/forgotPasswordTitleIc.svg
  src/assets/icon/requestResetPasswordDefaultBtnIc.svg
  src/assets/icon/requestResetPasswordProducerBtnIc.svg
  src/assets/icon/requestResetPasswordVocalBtnIc.svg
  src/assets/icon/resendPasswordProducerBtnIc.svg
  src/assets/icon/resendPasswordVocalBtnIc.svg
  src/assets/index.ts
  src/core/api/newPassword.ts
  src/utils/hooks/useSendNewPasswordEmail.ts
Labels: feat-UI, feat-function, 명헌

#223 Feat#222 common/api patch
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/login/loginInput.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/profileEditPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/Router.tsx
  src/assets/icon/profileEditBtnIc.svg
  src/assets/index.ts
  src/core/api/producerProfile.ts
  src/core/api/vocalProfile.ts
  src/type/producerProfile.ts
Labels: fix, refactor, 지영

#220 Feat#218 qa/responsive
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/mainHeader.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/@common/uploadInfo.tsx
  src/@components/login/loginInput.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/signUp/sendCodeButton.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/signUp/signupRole.tsx
  src/@components/signUp/verifyButton.tsx
  src/@components/trackPost/commentHeader.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/trackListHeader.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/upload/vocalUpload.tsx
  src/@components/vocalSearch/vocalListHeader.tsx
  src/@pages/loginPage.tsx
  src/@pages/mainPage.tsx
  src/@pages/signUpPage.tsx
  src/style/globalStyle.ts
Labels: feat-UI, 지수

#221 Feat#219 common
  src/@components/@common/mainHeader.tsx
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/login/loginInput.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@pages/forgotPasswordPage.tsx
  src/@pages/resetPasswordPage.tsx
  src/assets/image/subBackgroundImg.png
  src/core/api/resetPassword.ts
  src/utils/hooks/useSendNewPasswordEmail.ts
Labels: feat-UI, feat-function, 명헌

#228 Qa#224 signUp/complete
  src/@pages/signUpPage.tsx
Labels: fix, 지수

#235 Qa#234 common/profile path
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 지영

#237 [ feat ] 회원가입 이동 라우터 설정
  src/@components/login/loginInput.tsx
Labels: feat-function, 명헌

#227 Qa#226 main/user info
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/core/api/trackPost.ts
Labels: fix, 지영

#243 Qa#238 forgot password/message state
  public/index.html
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/utils/hooks/useSendNewPasswordEmail.ts
Labels: feat-UI, feat-function, refactor, 명헌

#248 Qa#236 trackpost/edit
  src/@components/trackPost/editDropDown.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/Router.tsx
Labels: feat-UI, 지영

#262 Qa#261 sign up/success
  src/@components/signUp/signupSuccess.tsx
Labels: fix, 지수

#265 [ fix ] 서버데이터 변경으로 wavFile -> audioFile로 변경 및 에러케이스 수정
  src/@components/@common/uploadHeader.tsx
  src/@components/@common/uploadInfo.tsx
  src/@pages/uploadPage.tsx
  src/core/api/upload.ts
  src/type/uploadData.ts
  src/type/uploadInfoDataType.ts
Labels: feat-function, fix, refactor, 명헌

#266 Qa#258 profile/hashtag
  src/@components/main/produderBriefInfo.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/signUp/signupProfile.tsx
  src/assets/icon/profileHashtagXIc.svg
  src/assets/index.ts
Labels: feat-UI, fix, 지수

#263 Qa#251 reset password/api
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@pages/resetPasswordPage.tsx
  src/core/api/resetPassword.ts
  src/core/api/validateResetPasswordToken.ts
  src/utils/hooks/useMovePage.ts
Labels: fix, refactor, 명헌

#283 Qa#280 upload/api
  src/@components/@common/portfolioViewMoreButton.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/upload/trackUpload.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/upload/uploadInfo.tsx
  src/@components/upload/vocalUpload.tsx
  src/@pages/uploadPage.tsx
  src/core/api/upload.ts
  src/type/uploadInfoDataType.ts
Labels: feat-function, fix, 명헌

#284 Qa#279 track post/comment post
  package.json
  src/@components/trackPost/commentUpdate.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/userComment.tsx
  src/assets/icon/commentUpldatCompleteIc.svg
  src/assets/index.ts
  src/core/api/trackPost.ts
  src/type/uploadDataType.ts
  src/type/userCommentsType.ts
  yarn.lock
Labels: fix, 지수

#286 Qa#285 track post/comment update
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
  src/core/api/trackPost.ts
Labels: fix, 지수

#290 Qa#236 trackpost/edit
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/core/api/trackPost.ts
Labels: feat-UI, feat-function, 지영

#288 Qa#287 track post/comment delete
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/userComment.tsx
  src/core/api/trackPost.ts
Labels: fix, 지수

#292 Qa#289 comment/bugs
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/trackPost/commentUpdate.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/trackSearch/trackList.tsx
  src/assets/icon/fileUploadButtonIc.svg
  src/assets/icon/pauseButtonIc.svg
  src/assets/index.ts
Labels: feat-function, fix, 지수

#294 Qa#293 comment/post bug
  src/@components/trackPost/commentUpdate.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/userComment.tsx
Labels: fix, 지수

#296 Qa#282 producer profile/data
  src/@pages/producerProfilePage.tsx
Labels: feat-function, fix, 예원

#299 Qa#295 track post/download
  package.json
  src/@pages/trackPostPage.tsx
  src/core/api/trackPost.ts
  yarn.lock
Labels: feat-function, fix, 지수

#303 Qa#300 download/bugs
  package.json
  src/@pages/trackPostPage.tsx
  src/core/api/trackPost.ts
  yarn.lock
Labels: fix, 지수

#305 Qa#304 sign up/bugs
  src/@components/signUp/producerUploadModal.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/signUp/signupSuccess.tsx
Labels: fix, 지수

#309 Qa#306 common/responsive
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/login/loginInput.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/trackPostPage.tsx
  src/mocks/categoryDummy.json
Labels: feat-UI, fix, 지수

#312 Qa#297 producer profile/data
  src/@pages/producerProfilePage.tsx
Labels: feat-function, fix, 예원

#311 Qa#310 login/bugs
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/login/loginInput.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@pages/forgotPasswordPage.tsx
  src/@pages/resetPasswordPage.tsx
  src/Router.tsx
  src/assets/icon/changePasswordConfirmIc.svg
  src/assets/icon/changePasswordNewPasswordIc.svg
  src/assets/icon/forgotPasswordEmailAskIc.svg
  src/assets/index.ts
Labels: feat-function, fix, 지수

#315 Qa#297 producer profile/data
  src/@pages/producerProfilePage.tsx
Labels: feat-function, fix, 예원

#316 Qa#314 header/bugs
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@pages/resetPasswordPage.tsx
  src/recoil/categorySelect.ts
Labels: fix, 지수

#318 Qa#291 common/api patch
  src/@components/@common/profileEditInfo.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/profileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/core/api/myPage.ts
Labels: fix, 지영

#320 Qa#317 portfolio/bugs
  src/@components/@common/portfoliosInform.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: feat-UI, fix, 지수

#322 Qa#321 portfolio/bugs
  src/@components/@common/backButton.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfolioViewMoreButton.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/signUp/signUpBackButton.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalProfilePage.tsx
  src/assets/icon/backButtonIc.svg
  src/assets/index.ts
  src/type/profilePropsType.ts
Labels: fix, 지수

#326 Qa#297 producer profile/data
  src/@pages/producerProfilePage.tsx
Labels: feat-function, fix, 예원

#327 Qa#323 profile/bugs
  src/@components/@common/backButton.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/@common/profileEditInfo.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@components/profileEdit/profileEditHeader.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@pages/profileEditPage.tsx
Labels: feat-UI, fix, 지수

#329 [ fix ] 타이틀 안 뜨는 문제 해결
  src/@components/@common/portfoliosInform.tsx
Labels: fix, 지수

#331 QA#330 trackSearch/infinite
  src/@pages/trackSearchPage.tsx
Labels: fix, 예원

#333 Qa#324 upload/bugs
  src/@components/@common/tracksProfileUploadModal.tsx
  src/@components/upload/trackUpload.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/upload/uploadInfo.tsx
  src/@components/upload/vocalUpload.tsx
Labels: feat-UI, fix, 지수

#334 Qa#325 signup/bugs
  src/@components/signUp/conventionCheckBox.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@pages/signUpPage.tsx
  src/type/signUpStepTypes.ts
Labels: fix, 지수

#337 Qa#332 track search/get data
  src/@components/@common/categoryHeader.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/utils/hooks/useInfiniteKey.ts
Labels: feat-function, fix, refactor, 예원

#342 Qa#341 profile/bugs
  src/@components/producerProfile/producerInfos.tsx
Labels: fix, 지수

#345 Qa#340 vocal profile/infinite scroll
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
Labels: feat-function, fix, 예원

#346 Qa#339 track search/filtering
  src/@pages/producerProfilePage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 지수

#349 Qa#348 vserror
  src/@components/trackSearch/trackList.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 예원
