Repository Track-1/client, pull requests merged in 2023-04, with the labels that each got.

#352 Qa#350 common/fix
  src/@components/@common/portfoliosInform.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/conventionCheckBox.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/trackPost/commentUpdate.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/resetPasswordPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/core/api/common/axios.ts
  src/core/api/logout.ts
  src/core/api/myPage.ts
  src/core/api/producerProfile.ts
  src/core/api/profile.ts
  src/core/api/signUp.ts
  src/core/api/trackPost.ts
  src/core/api/vocalProfile.ts
  src/utils/hooks/usePlayerInfos.ts
Labels: refactor, 지영

#358 Qa#357 profile/null page
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 지수

#363 Qa#353 common/patch fix
  src/@components/@common/profileEditInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 지영

#367 Qa#364 track search/filter
  src/@components/@common/categoryList.tsx
  src/@components/upload/uploadHeader.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/core/api/upload.ts
Labels: feat-function, fix, 지영

#372 Qa#359 comment/infinite
  src/@components/trackPost/userComment.tsx
  src/@pages/trackSearchPage.tsx
  src/core/api/trackPost.ts
Labels: feat-function, fix, 예원

#371 [ fix ] patch api오류 해결
  src/@components/@common/backButton.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/core/api/trackPost.ts
  src/type/producerProfile.ts
Labels: fix, 지영

#380 [ feat ] 프로필 수정 서버 변경 반영
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
Labels: fix, 지영

#387 Qa#386 comment
  src/@components/trackPost/commentUpdate.tsx
  src/@components/trackPost/userComment.tsx
Labels: feat-function, fix

#391 Qa#384 sign up/bugs
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/signUp/sendCodeButton.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/signUp/signupRole.tsx
  src/@pages/signUpPage.tsx
  src/assets/icon/signupCompleteBtnIc.svg
  src/assets/index.ts
  src/core/userInfoErrorMessage/passwordInvalidMessage.ts
  src/utils/errorMessage/checkPasswordForm.ts
Labels: fix, 지수

#393 Qa#392 back btn/bugs
  src/@components/@common/backButton.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/profileEdit/profileEditHeader.tsx
  src/@components/upload/uploadHeader.tsx
  src/@pages/forgotPasswordPage.tsx
  src/@pages/loginPage.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
Labels: fix, 지수

#401 Qa#400 edit page/bugs
  src/@components/@common/profileEditInfo.tsx
  src/@components/@common/profileWarning.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/profileEdit/profileEditHeader.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/trackPost/hashTag.tsx
  src/@components/upload/uploadInfo.tsx
  src/@pages/loginPage.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
Labels: feat-UI, fix, 지수

#403 Qa#398 producer/profile
  src/@components/producerProfile/producerInfos.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: feat-function, 예원

#404 Qa#402 common/private
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/@components/@common/mainHeader.tsx
  src/@components/@common/profileEditInfo.tsx
  src/@components/login/loginInput.tsx
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/@components/trackPost/hashTag.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/trackSearch/trackList.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/signUpPage.tsx
  src/@pages/trackPostPage.tsx
  src/Router.tsx
  src/utils/common/isLogined.ts
  src/utils/common/privateRoute.tsx
Labels: feat-UI, feat-function, fix, 지수

#406 Qa#397 track post/comment
  package.json
  public/mockServiceWorker.js
  src/@components/@common/categoryList.tsx
  src/@components/@common/player.tsx
  src/@components/signUp/profilImageContainer.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalsPage.tsx
  src/core/api/vocalSearch.ts
  src/index.tsx
  src/mocks/browser.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/myPage.ts
  src/mocks/handlers/producerProfile.ts
  src/mocks/handlers/trackPost.ts
  src/mocks/handlers/trackSearch.ts
  src/mocks/handlers/trackUpload.ts
  src/mocks/handlers/vocalProfile.ts
  src/mocks/handlers/vocalSearch.ts
  src/utils/hooks/usePlayerInfos.ts
  yarn.lock
Labels: fix, 지영

#408 [ fix ] 보컬서칭 trackSearching 필터링 기능 구현
  src/@components/@common/categoryList.tsx
  src/core/api/vocalSearch.ts
Labels: feat-function, fix, 지영

#414 Qa#413 comment/profile image
  src/@components/trackPost/commentUpdate.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/eachUserComment.tsx
  src/@components/trackPost/userComment.tsx
Labels: fix, 예원

#420 Qa#405 common/bugs
  src/@components/signUp/signupRole.tsx
  src/@pages/trackPostPage.tsx
  src/core/api/trackPost.ts
  src/core/api/vocalSearch.ts
Labels: fix, 지수

#423 Qa#409 vocal search/fix
  src/@components/@common/loading.tsx
  src/@components/trackPost/userComment.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/vocalSearch/vocalList.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/image/loading.gif
  src/type/vocalSearchType.ts
  src/type/vocalsDataType.ts
Labels: feat-UI, fix, 지영

#427 Qa#422 common/etc
  src/@components/@common/portfolioViewMoreButton.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/signupNicknameConvention.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/upload/uploadInfo.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 지수

#428 Qa#421 main page/UI
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
Labels: fix, 예원

#432 Qa#419 data reload
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/upload/uploadHeader.tsx
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfilePage.tsx
Labels: fix, 명헌

#436 Qa#435 profile edit/name
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
Labels: feat-UI, 예원

#440 [ feat ] state값 추가로 제대로 이동하도록 함.
  src/@pages/trackPostPage.tsx
Labels: fix, 예원

#442 Qa#441 track search/category
  src/@components/@common/categoryList.tsx
  src/@components/trackSearch/trackList.tsx
  src/@pages/trackSearchPage.tsx
Labels: feat-function, fix, 예원

#443 Qa#426 common/browser back
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/trackSearch/trackList.tsx
  src/@pages/mainPage.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/uploadPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/@pages/vocalsPage.tsx
  src/recoil/main.ts
  src/utils/hooks/useBrowserBack.ts
  src/utils/hooks/usePlayer.ts
Labels: fix, 지수

#451 Qa#449 common/post fix
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/producerProfile/producerInfos.tsx
  src/@components/trackSearch/uploadButtonModal.tsx
  src/@components/upload/uploadHeader.tsx
  src/@pages/mainPage.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/producerProfilePage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/uploadPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/@pages/vocalProfilePage.tsx
  src/core/api/trackPost.ts
  src/core/api/upload.ts
  src/core/api/vocalSearch.ts
Labels: fix, 지영

#450 Qa#448 error/page
  src/@pages/errorPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/Router.tsx
  src/assets/icon/errorPageIc.svg
  src/assets/index.ts
Labels: feat-UI, feat-function, 지수

#461 [ fix ] 리로드 잘못된 코드 수정
  src/@pages/vocalsPage.tsx
Labels: fix, 지수

#464 [ fix ] 포트폴리오에서 트랙포스트로 갈 때 음악 멈추도록 구현
  src/@components/@common/portfoliosInform.tsx
  src/@pages/trackPostPage.tsx
  src/recoil/main.ts
Labels: fix, 지수

#467 Qa#466 track post/post fix
  src/@components/@common/loading.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/portfoliosInform.tsx
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/login/loginInput.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/trackPost/editDropDown.tsx
  src/@components/trackPost/userComment.tsx
  src/@pages/resetPasswordPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/trackPostPage.tsx
  src/@pages/trackSearchPage.tsx
  src/@pages/vocalsPage.tsx
  src/assets/image/loading.gif
Labels: feat-UI, fix, 지영

#469 Qa#468 vocal portfolio/delete
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/trackPost/eachUserComment.tsx
Labels: fix, 예원

#470 Qa#445 UI
  src/@components/trackPost/eachUserComment.tsx
Labels: fix, 예원

#472 [ feat ] hover시 이미지 추가
  src/@components/trackPost/eachUserComment.tsx
Labels: fix, 예원

#478 Qa#425 upload/UI
  src/@components/upload/uploadInfo.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
Labels: fix, 지수

#477 [ fix ] 페이지 이동 시에도 필터링 유지
  src/@components/@common/categoryHeader.tsx
  src/@components/@common/categoryList.tsx
  src/recoil/categorySelect.ts
Labels: fix, 지수

#481 Qa#479 common/etc
  src/@components/vocalProfile/vocalProfileList.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/uploadPage.tsx
  src/utils/hooks/useBrowserBack.ts
Labels: feat-UI, fix, 지수

#485 [ feat ] trackPost api 헤더 쿠키 설정
  src/core/api/trackSearch.ts
Labels: fix, 예원

#493 Qa#491 test/etc
  src/@components/trackPost/eachUserComment.tsx
  src/@components/upload/uploadInfo.tsx
  src/@pages/trackPostEditPage.tsx
Labels: fix, 지수

#495 Qa#489 etc
  src/@components/trackPost/userComment.tsx
Labels: fix, 명헌

#504 Qa#501 description
  src/@components/@common/profileEditInfo.tsx
  src/@components/signUp/signupProfile.tsx
  src/utils/hooks/useTextareaHeight.ts
Labels: feat-function, 예원

#503 [ fix ] 크롬 자동저장 막기
  src/@components/signUp/SignupEmailPassword.tsx
  src/@pages/signUpPage.tsx
Labels: fix, 지수

#512 Qa#506 common/final
  src/@components/producerProfile/producerInfos.tsx
  src/@components/signUp/signupMessage.tsx
  src/@components/signUp/signupSuccess.tsx
  src/@pages/signUpPage.tsx
  src/@pages/uploadPage.tsx
Labels: fix, 지수

#518 [ feat ] profileEditInfo 디스크립션 수정
  src/@components/@common/profileEditInfo.tsx
  src/utils/hooks/useTextareaHeight.ts
Labels: feat-function, 예원

#521 Qa#519 upload/sign up/re merge
  src/@components/signUp/signupProfile.tsx
  src/@components/upload/uploadInfo.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/utils/hooks/useTextareaHeight.ts
Labels: feat-function, fix, 예원

#522 [ fix ] blackIcon 조건 변경
  src/@components/@common/portfoliosInform.tsx
Labels: fix, 명헌

#527 [ fix ] 프로듀서,보컬, 포트폴리오, 보컬서칭 별로 삭제 조건추가
  src/@components/@common/portfolioUpdateModal.tsx
Labels: fix

#528 Qa#524 common/alert
  src/@components/@common/categoryList.tsx
  src/@components/@common/portfolioUpdateModal.tsx
  src/@components/@common/profileEditInfo.tsx
  src/@components/main/produderBriefInfo.tsx
  src/@components/main/vocalBriefInfo.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@components/signUp/SignupEmailPassword.tsx
  src/@components/signUp/signUpBackButton.tsx
  src/@components/signUp/signupProfile.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@components/trackPost/editDropDownComment.tsx
  src/@components/upload/uploadInfo.tsx
  src/@pages/producerPortfolioEditPage.tsx
  src/@pages/producerProfileEditPage.tsx
  src/@pages/trackPostEditPage.tsx
  src/@pages/vocalPortfolioEditPage.tsx
  src/@pages/vocalProfileEditPage.tsx
  src/core/api/common/axios.ts
  src/style/globalStyle.ts
  src/utils/common/privateRoute.tsx
  src/utils/uploadPage/uploadImage.ts
Labels: feat-UI, fix, 지수

#532 Qa#531 common/input
  src/@components/login/loginInput.tsx
  src/@components/profileEdit/producerProfileEditTitle.tsx
  src/@components/profileEdit/vocalProfileEditTitle.tsx
  src/style/globalStyle.ts
Labels: feat-UI, fix, 지수

#534 [ fix ] 인풋 히든 스타일링
  src/@components/login/loginInput.tsx
Labels: feat-UI, fix, 지수

#536 [ fix ] 패스워드 저장 로직 수정
  src/@components/login/loginInput.tsx
Labels: feat-UI, fix, 지수

#539 Qa#537 common/final qa
  src/@components/producerProfile/producerPortFolioList.tsx
  src/@components/trackPost/commentWrite.tsx
  src/@pages/trackPostPage.tsx
Labels: fix, 지수

#543 [ refactor ] setCookie -> recoil로 상태관리 변경
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@components/resetPassword/resetPasswordInput.tsx
  src/@pages/forgotPasswordPage.tsx
  src/@pages/resetPasswordPage.tsx
  src/Router.tsx
  src/core/api/resetPassword.ts
  src/core/api/validateResetPasswordToken.ts
  src/recoil/forgotPasswordToken.ts
  src/utils/hooks/useSendNewPasswordEmail.ts
Labels: fix, refactor, 명헌

#544 [ fix ] 페이지가 이동하면서 recoil 값이 초기화되는 이슈 해결
  src/recoil/forgotPasswordToken.ts
Labels: fix, 명헌

#549 [ fix ] 뷰모어 버튼 안 뜨는 문제 해결
  src/@components/@common/portfoliosInform.tsx
Labels: fix, 지수

#552 Qa#550 axios/refresh
  src/@components/forgotPassword/forgotPasswordInput.tsx
  src/@pages/resetPasswordPage.tsx
  src/Router.tsx
  src/core/api/common/axios.ts
Labels: fix, 명헌

#553 Qa#551 common/UI fix
  public/index.html
  src/@components/trackPost/userComment.tsx
Labels: feat-function, fix, 지영

#554 [ etc ] resetPassword 페이지 렌더링 될때 useParms를 이용해 토큰값 전달
  src/@pages/resetPasswordPage.tsx
  src/core/api/validateResetPasswordToken.ts
Labels: fix, 명헌

#557 Qa#556 error/UI
  src/@pages/errorPage.tsx
  src/assets/icon/errorPageMainIc.svg
  src/assets/icon/errorPageTextIc.svg
  src/assets/index.ts
Labels: feat-UI, 지수

#559 Qa#558 portfolio/hover
  src/@components/producerProfile/producerPortFolioList.tsx
Labels: fix, 지수

#561 [ fix ] 어드민 이메일 주소 수정
  src/@components/@common/footer.tsx
  src/@pages/errorPage.tsx
Labels: fix, 지수

#563 [ fix ] trackPostPage 접근 오류 수정
  src/@pages/trackPostPage.tsx
Labels: fix, 지영

#567 [ fix ] 로그인 하지 않고 프로듀서 프로필 페이지 접근 시 음악 멈추도록 구현
  src/@pages/trackPostPage.tsx
Labels: fix, 지수

#573 [ fix ] vocalProfilePage 접근 오류 수정
  src/@pages/vocalProfilePage.tsx
Labels: fix, 지영

#575 [ fix ] 프로듀서 프로필 페이지 경로 수정
  src/@pages/producerProfilePage.tsx
Labels: fix

#577 [ fix ] 회원가입 비밀번호 한글 입력 안 되도록 수정
  src/@components/signUp/SignupEmailPassword.tsx
Labels: fix, 지수

#579 Qa#578 sign up/special
  src/core/userInfoErrorMessage/passwordInvalidMessage.ts
  src/utils/errorMessage/checkPasswordForm.ts
Labels: fix, 지수

#581 [ etc ] 비밀번호 오류 메시지 수정
  src/core/userInfoErrorMessage/passwordInvalidMessage.ts
Labels: fix, 지수

#583 [ feat ] GTM코드 삽입
  public/index.html
Labels: feat-function, 지영
